openshift/ci-operator/knative-images/broker-dispatcher/Dockerfile, openshift/ci-operator/knative-images/broker-receiver/Dockerfile
Signed-off-by: Pierangelo Di Pilato <pdipilat@redhat.com>
=> Fix data plane image builds

hack/run.sh, test/e2e-common.sh
=> [release-v0.26] Separate step for just launching Kafka cluster (Strimzi)

openshift/e2e-common.sh, openshift/e2e-tests.sh, openshift/release/create-release-branch.sh, openshift/release/generate-release.sh, openshift/release/knative-eventing-kafka-broker-cp-ci.yaml, openshift/release/knative-eventing-kafka-broker-dp-ci.yaml, openshift/release/mirror-upstream-branches.sh, openshift/release/resolve.sh, openshift/release/update-to-head.sh
This install the broker, based on our own CI yaml
If this all passes, next PR will work on the e2e tests
=> [release-v0.26] Adding release build scripts and install broker

control-plane/config/100-config-logging.yaml, openshift/release/knative-eventing-kafka-broker-cp-ci.yaml
=> Add missing cm

openshift/e2e-common.sh, openshift/e2e-tests.sh, test/e2e/broker_trigger_sink_test.go, test/e2e/kafka_sink_test.go, test/e2e/sacura_test.go
=> Override image template and run e2e tests

control-plane/cmd/kafka-controller/main.go
=> [release-v0.26] Comment out sink ctrl

openshift/e2e-common.sh, openshift/e2e-tests.sh, vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml, vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml, vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml, vendor/knative.dev/reconciler-test/pkg/images/ko.go
=> E2E_new test suite execution

openshift/release/generate-release.sh
=> Not always appending to manifests

openshift/e2e-tests.sh, test/kafka/kafka_setup.sh
as per title
(and a little fix for deprecated client usage)
=> [release-v1.0] Reorder scripts

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/RecordDispatcherListener.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractOffsetManagerTest.java
=> [release-v0.26] BACKPORT: Commit offset on consumer close

openshift/ci-operator/build-image/Dockerfile
related to https://github.com/openshift-knative/serverless-operator/pull/1302
Let's see how this really goes...
=> [release-v0.26] Golang 1.17 container image

openshift/ci-operator/build-image/Dockerfile
backport of https://github.com/openshift-knative/eventing-kafka-broker/pull/29
=> [release-v1.0] Golang 1.17 container image

openshift/ci-operator/build-image/Dockerfile
=> Remove ansible

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/InvalidCloudEventInterceptor.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/KafkaConsumerRecordUtils.java, data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1500
=> [release-v1.0] Properly handle events without the `data` field

openshift/ci-operator/knative-images/sink-receiver/Dockerfile, openshift/ci-operator/knative-images/sink-receiver/generate_jdk.sh, openshift/release/generate-release.sh, openshift/release/knative-eventing-kafka-broker-cp-ci.yaml, openshift/release/knative-eventing-kafka-broker-dp-ci.yaml, openshift/release/resolve.sh
starting work to get the kafka sink in place
Next: openshift release repo: image build
=> Adding Kafka Sink

openshift/ci-operator/knative-images/broker-dispatcher/Dockerfile, openshift/ci-operator/knative-images/broker-receiver/Dockerfile
=> Using UBI 8 with OpenJDK-17 image as Runtime :penguin: (#43)

test/e2e/broker_trigger_sink_test.go, test/e2e/kafka_sink_test.go
=> [release-v1.0] :detective: some more tests for KafkaSink enabled

openshift/e2e-common.sh, openshift/e2e-tests.sh
=> [release-v1.0] Adding conformance tests

OWNERS
I arguably shouldn't have been on here anyway, so might as well starting the cleanup early.
/assign @devguyio @matzew
=> [RELEASE-v1.0] Remove myself from OWNERS

OWNERS
I arguably shouldn't have been on here anyway, so might as well starting the cleanup early.
/assign @devguyio @matzew
=> [RELEASE-v0.26] Remove myself from OWNERS

Makefile, openshift/e2e-conformance-tests.sh, openshift/e2e-tests.sh
Do not merge - 
This is a test to run the conformance _isolated_ - if all good - a new "target" on openshift/releae will be created
=> [release-v1.0] testing separation

vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml, vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml, vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Do not use the nightly - We change them now manually. Eventually that will be all automated.
=> [release-v1.0] Actual version for rekt test

vendor/knative.dev/pkg/injection/interface.go, vendor/knative.dev/pkg/injection/sharedmain/main.go
=> [release-v1.0] Backporting PR 2339 from knative/pkg to our vendor folder

test/pkg/broker/broker.go, test/pkg/testing/run.go, third_party/VENDOR-LICENSE/github.com/nxadm/tail/ratelimiter/Licence
Backport of upstream https://github.com/knative-sandbox/eventing-kafka-broker/pull/1594
=> [release-v0.26] Use Broker's own configmap for Kafka

control-plane/pkg/reconciler/trigger/controller.go, control-plane/pkg/reconciler/trigger/controller_test.go
Cherry-pick of: https://github.com/knative-sandbox/eventing-kafka-broker/pull/1597
=> [release-v0.26] [SRVKE-1074] Remove Trigger finalizer when Broker is removed (#1597)

control-plane/cmd/kafka-controller/main.go, vendor/knative.dev/pkg/injection/sharedmain/main.go
a  little more tweaking on the vendor'ed dependency
=> Use namedMain and patch vendor lib

control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/trigger/controller.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1621
/assign @aliok @devguyio
=> [release-1.0] Add promote filter function to Broker and Trigger reconciler

openshift/e2e-common.sh
=> [release-0.26] Checkout Serverless Operator 1.20 branch

control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/trigger/controller.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1653
=> [release-v0.26] Add promote filter function to Broker and Trigger reconciler

Makefile, openshift/ci-operator/Dockerfile.in, openshift/ci-operator/build-image/Dockerfile, openshift/ci-operator/generate-ci-config.sh, openshift/ci-operator/generate-dockerfiles.sh, openshift/ci-operator/update-ci.sh, openshift/e2e-common.sh, openshift/e2e-conformance-tests.sh, openshift/e2e-tests.sh, openshift/release/create-release-branch.sh, openshift/release/generate-release.sh, openshift/release/mirror-upstream-branches.sh, openshift/release/resolve.sh, openshift/release/update-to-head.sh
Preparing work for new release 1.1  and the `release-next` nightly setup.
Step 1: sync main with what we have from last release (1.0) branch
=> Sync main with latest script from production release 1.0

openshift/ci-operator/generate-ci-config.sh
=> This line was accidentally removed

hack/data-plane.sh, test/e2e/broker_trigger_sink_test.go, test/e2e/kafka_sink_test.go, test/e2e/sacura_test.go, vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml, vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml, vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml, vendor/knative.dev/reconciler-test/pkg/images/ko.go
As per title: more patches 
will be sorted for `release-next`, in a couple of days
=> Release v1.1 more things to patch

openshift/e2e-common.sh
=> [release-v1.1] We only have generic receivers and dispatchers 

openshift/ci-operator/knative-images/dispatcher/Dockerfile, openshift/ci-operator/knative-images/dispatcher/generate_jdk.sh, openshift/ci-operator/knative-images/receiver/Dockerfile, openshift/ci-operator/knative-images/receiver/generate_jdk.sh
For convenience reasons adding the Data Plane images here as static files.
=> Adding static DP images, for now

openshift/release/generate-release.sh
same like:
https://github.com/openshift/knative-eventing/pull/1593
=> Remove knative- from the release generator script

openshift/release/generate-release.sh, openshift/release/knative-eventing-kafka-broker-dp-ci.yaml
Adding the channel to the generator, and regenerate the manifests
=> [release-v1.2] add channel manifests

hack/data-plane.sh, openshift/e2e-common.sh, test/e2e/broker_trigger_sink_test.go, test/e2e/kafka_sink_test.go, test/e2e/sacura_test.go, vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml, vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml, vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml, vendor/knative.dev/reconciler-test/pkg/images/ko.go
Bringing forward some patches from 1.1 branch  (eventually they will be automated)
/hold
=> Release v1.2 patch apply

openshift/release/mirror-upstream-branches.sh
* take into account branches starting with release-v1.
* fix the behavior when multiple new branches are found upstream (use
arrays for them)
* take into account two types of naming scheme for upstream tags:
knative-v.X.X.X and v.X.X.X (change in naming since 1.x)
Fixes errors like this one: https://master-jenkins-csb-serverless-qe.apps.ocp-c1.prod.psi.redhat.com/job/ci/job/knative-nightly-ci-eventing-kafka-broker/1/console
Related Slack thread: https://coreos.slack.com/archives/CEXRYS5QC/p1643729504198209
=> Fix mirror-upstream-branches.sh

test/e2e_new/features/broker_deleted_recreated.go, test/e2e_new/features/featuressteps/broker.go
=> [release-v1.1] Delete broker only (#1848)

openshift/e2e-common.sh
=> Increase timeout for E2E tests

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/channel/channel_test.go, control-plane/pkg/reconciler/sink/kafka_sink.go, control-plane/pkg/reconciler/sink/kafka_sink_test.go, test/upgrade-tests.sh
bringing https://github.com/knative-sandbox/eventing-kafka-broker/pull/1883  to midstream
=> [release-1.1] Do not delete finalizer until the probe returns status not ready

hack/update-checksums.sh, openshift/patches/disable-ko-publish-rekt.patch, openshift/patches/main-named-to-disable-controllers.patch, openshift/patches/override-min-version.patch, openshift/patches/override-rekt-images.patch, openshift/release/create-release-branch.sh, openshift/release/generate-release.sh, openshift/release/knative-eventing-kafka-broker-cp-ci.yaml, openshift/release/knative-eventing-kafka-broker-dp-ci.yaml, openshift/release/resolve.sh, openshift/release/update-to-head.sh
See individual commits.
TODO:
- Port this to main and other branches
=> [release-v1.0] Add patches and fix generate release

openshift/ci-operator/generate-ci-config.sh
Same as:
https://github.com/openshift/knative-eventing/commit/a94c97bf2a877c45a8291806e78a3baea0bb8b92
See https://github.com/openshift/release/pull/26101
=> Change Mem and CPU for CI jobs

openshift/ci-operator/generate-ci-config.sh
This is a cherry-pick of https://github.com/openshift-knative/eventing-kafka-broker/pull/117
=> [release-v1.0] Change Mem and CPU for CI jobs

openshift/ci-operator/update-ci.sh
=> Slack reporter uses knative-eventing-ci

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/ResponseFailureException.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/6396bd16e0745ad7e35d7f21e7da92983a212e55
=> [SRVKE-1164] [release-v1.0] Fix class cast exception (#1945)

openshift/release/knative-eventing-kafka-broker-cp-ci.yaml
=> Regenerate yamls

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/testing/objects_broker.go
Back port of upstream 1971 PR to our midstream
=> [release-v1.1] Use broker status annotations to stamp ConfigMap reference

control-plane/pkg/reconciler/broker/broker.go
Bringing in support for external managed topics.
PR is pending upstream.
But we need this here too...
=> [release-v1.1] Get external topics

openshift/ci-operator/build-image/kubernetes.repo
=> [release-v1.0] Skip GPG check for kubernetes repository

openshift/ci-operator/build-image/kubernetes.repo
=> [release-v1.1] Skip GPG check for kubernetes repository

openshift/ci-operator/build-image/kubernetes.repo
=> [release-v0.26]  Skip GPG check for kubernetes repository

test/test_images/kafka-consumer/consumer.go
=> [release-v1.2] Fix recent import change 

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticleTest.java
Cherry-pick https://github.com/knative-sandbox/eventing-kafka-broker/commit/84ab89b7eba5e130b2b4d576a042e1487f93a53e
=> [release-v1.1] Poll for new records when `max.poll.records` limit isn't reached (#2003)

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/ResponseToKafkaTopicHandler.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticleTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
Depends on https://github.com/openshift-knative/eventing-kafka-broker/pull/156
Cherry-pick:
- https://github.com/openshift-knative/eventing-kafka-broker/commit/c9fa324eb78b5d8f5aa39896f13a08a95ab9c6f5
=> [v1.2] Improve dispatcher components stop lifecycle

OWNERS
=> Remove devguyio from OWNERS_ALIASES

Makefile, openshift/release/generate-release.sh
=> [release-v1.3] Build post-install job

control-plane/cmd/post-install/main.go
=> [release-v1.1] Include error in error message of the SO deleter

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
=> [release-v1.2] :cherry: pick of 2064

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/4f587412e60e4eac848fa894c7de8acf25610e2b
* Handle cases when there is no committed offset
Calling `committed()` on an fresh consumer produces no
`OffsetAndMetadata`, so we shouldn't rely on this to get the
committed offset.
* Use debug level
Co-authored-by: Pierangelo Di Pilato <pierdipi@redhat.com>
=> [release-v1.1] Handle cases when there is no committed offset (#2075)

.gitignore, openshift/e2e-common.sh
Run tests only once.
See individual commits for details
/cc @matzew
=> Run tests only once

openshift/e2e-common.sh
Using 1.21 product branch for here
=> [release-v1.0] use matching product for this branch

openshift/e2e-common.sh
Using 1.22 product branch for here
=> [release-v1.1] use matching product for this branch

test/upgrade/continual/broker.go
Fixes https://github.com/openshift-knative/serverless-operator/pull/1513#issuecomment-1099014668
=> Fix wrong kafka import

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
Cherry-pick of https://github.com/openshift-knative/eventing-kafka-broker/commit/b9efc80d21e1e139eed0874184047aea66002466 and https://github.com/openshift-knative/eventing-kafka-broker/commit/0024c7e0edc47965b4f84c700bec3379c818e88e
=> [release-v1.3] Handle cases when there is no committed offset (#2075)

control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-source-defaults.yaml, openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-channel.yaml, openshift/release/artifacts/eventing-kafka-controller.yaml, openshift/release/artifacts/eventing-kafka-post-install.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml, openshift/release/artifacts/eventing-kafka-source.yaml, openshift/release/resolve.sh
As in https://github.com/openshift-knative/serverless-operator/pull/1499 but for midstream
=> [release-v1.2] Add config-kafka-source-defaults ConfigMap

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml, openshift/e2e-common.sh, openshift/e2e-tests.sh, openshift/release/artifacts/eventing-kafka-controller.yaml
like #226
but different (removed the extra test suite)
=> Channel services cluster role

openshift/e2e-rekt-tests.sh, vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml, vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml, vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml, vendor/knative.dev/eventing/test/test_images/event-sender/pod.yaml, vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml, vendor/knative.dev/eventing/test/test_images/performance/pod.yaml, vendor/knative.dev/eventing/test/test_images/print/pod.yaml, vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml, vendor/knative.dev/eventing/test/test_images/request-sender/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-fetcher/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-forwarder/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-receiver/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-sender/pod.yaml, vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Adding better image version for vendor'ed rekt-test bits and adding a script for the rekt-tests execution
=> [release-v1.2] Prefactoring: Align rekt test resources

openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-channel.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml, openshift/release/artifacts/eventing-kafka-source.yaml
We will consume these manifests in the SO, hence putting these fixes here.
=> [release-v1.2] Adding disable fips for our midstream

openshift/e2e-common.sh, vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml, vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml, vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml, vendor/knative.dev/eventing/test/test_images/event-sender/pod.yaml, vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml, vendor/knative.dev/eventing/test/test_images/performance/pod.yaml, vendor/knative.dev/eventing/test/test_images/print/pod.yaml, vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml, vendor/knative.dev/eventing/test/test_images/request-sender/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-fetcher/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-forwarder/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-receiver/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-sender/pod.yaml, vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
* Align rekt test resources
* Better test failing
Little bit like #234
=> [release-v1.3] Prefactor new e2e 1.3

control-plane/pkg/security/secret.go, control-plane/pkg/security/secret_test.go, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuth.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidatorTest.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuthTest.java
=> [release-v1.2] Backport of 2139

Makefile, openshift/ci-operator/knative-test-images/eventshub/Dockerfile, openshift/e2e-common.sh
Doing the actual image build now, since this got merged:
* https://github.com/openshift/release/pull/28421
=> [release-v1.2] Build eventshub 

Makefile, openshift/ci-operator/knative-test-images/eventshub/Dockerfile, openshift/e2e-common.sh
Add support for building the eventshub for the broker
=> [release-v1.3] Build eventshub

openshift/patches/override-rekt-images.patch, vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
based on:
* https://github.com/openshift-knative/eventing-kafka-broker/pull/248
=> Update eventhubs patch 1.2

openshift/patches/override-rekt-images.patch, openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-channel.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml, openshift/release/artifacts/eventing-kafka-source.yaml, vendor/knative.dev/eventing-kafka/test/e2e/helpers/channel_subscription_ready_test_helper.go, vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml, vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml, vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml, vendor/knative.dev/eventing/test/test_images/event-sender/pod.yaml, vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml, vendor/knative.dev/eventing/test/test_images/performance/pod.yaml, vendor/knative.dev/eventing/test/test_images/print/pod.yaml, vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml, vendor/knative.dev/eventing/test/test_images/request-sender/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-fetcher/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-forwarder/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-receiver/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-sender/pod.yaml, vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
Similar like #247 but for the 1.3 branch
=> [release-v1.3] Adding correct coordinates for the versioned REKT TEST images

Makefile, openshift/e2e-common.sh, openshift/e2e-rekt-tests.sh
ADding new target for rekt tests
=> [release-v1.3] Adding new target for rekt tests

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
=> [release-v1.2] #Backport: Adding 408 to retry list

control-plane/pkg/prober/async_prober.go, control-plane/pkg/prober/async_prober_test.go, control-plane/pkg/prober/prober.go, control-plane/pkg/prober/prober_test.go, control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/channel/controller.go, control-plane/pkg/reconciler/sink/controller.go, data-plane/config/broker/500-receiver.yaml, data-plane/config/channel/500-receiver.yaml, data-plane/config/sink/500-receiver.yaml, openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-channel.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml
See commit for reference upstream PR
=> [v1.2] Prober targets service instead of pods directly (#2112)

go.mod, go.sum, vendor/knative.dev/eventing-kafka/pkg/channel/consolidated/reconciler/controller/resources/service.go, vendor/knative.dev/eventing-kafka/test/upgrade/continual/channel.go, vendor/modules.txt
/hold
until https://github.com/openshift-knative/eventing-kafka-broker/pull/252 is merged 
(will rebase than)
=> [release-v1.3] Manual dep bump for ocp 

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/OrderedAsyncExecutor.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandler.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/OrderedAsyncExecutorTest.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverEnvTest.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2145/files
=> [release-v1.2] Clean up ordered delivery verticle (#2145)

control-plane/pkg/reconciler/broker/broker.go
* move up the check if the topic is external, so we are not bothering w/ Sarama config call (for a non admin user)
/assign @pierDipi 
Next:  upstream polishing the _actual_ PR + adding test
=> [release-v1.1] Move up the check if topic is externally managed

data-plane/config/broker/500-dispatcher.yaml, data-plane/config/broker/500-receiver.yaml, data-plane/config/brokerv2/500-dispatcher.yaml, data-plane/config/channel/500-dispatcher.yaml, data-plane/config/channel/500-receiver.yaml, data-plane/config/channelv2/500-dispatcher.yaml, data-plane/config/sink/500-receiver.yaml, data-plane/config/source/500-dispatcher.yaml, data-plane/config/sourcev2/500-dispatcher.yaml, openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-channel.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml, openshift/release/artifacts/eventing-kafka-source.yaml
basically this contains:
* #269
* #270 
but for the 1.3.2 branch
=> [release-v1.3] backport manifest changes 

data-plane/config/broker/500-dispatcher.yaml, data-plane/config/broker/500-receiver.yaml, data-plane/config/brokerv2/500-dispatcher.yaml, data-plane/config/channel/500-dispatcher.yaml, data-plane/config/channel/500-receiver.yaml, data-plane/config/channelv2/500-dispatcher.yaml, data-plane/config/sink/500-receiver.yaml, data-plane/config/source/500-dispatcher.yaml, data-plane/config/sourcev2/500-dispatcher.yaml, openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-channel.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml, openshift/release/artifacts/eventing-kafka-source.yaml
Based on:
* https://github.com/openshift-knative/eventing-kafka-broker/pull/269
=> Fips patch ocp

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
We need to handle the case when the offset tracker was removed from
our Map since when partitions are revoked we remove the associated
offset tracker, however, we may get a response from the sink for a
previously owned partition after a partition has been revoked.
Note: it's not possible to commit offsets of partitions that a
particular consumer instance doesn't own.
Co-authored-by: Pierangelo Di Pilato <pierdipi@redhat.com>
=> [release v1.2] Handle committing offsets on revoked partitions

control-plane/pkg/reconciler/broker/broker.go
Backport feature for using external topics
actual PR in the works, upstream
=> External topic annotation 1.2

control-plane/config/post-install/200-controller-cluster-role.yaml, openshift/release/artifacts/eventing-kafka-post-install.yaml
=> [release-v1.2] Fix RBAC for deletion of configmaps

control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/channel/channel_test.go, control-plane/pkg/reconciler/testing/objects_common.go, control-plane/pkg/security/secrets_provider_legacy_channel_secret.go, test/e2e-common.sh, test/kafka/kafka_setup.sh
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2224
=> [release-v1.2] Support legacy KafkaChannel secret format

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/PartitionRevokedHandler.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2221
=> [release-v1.3] Commit offsets on partition revoked (#2221)

openshift/e2e-common.sh, openshift/e2e-conformance-tests.sh, openshift/e2e-rekt-tests.sh, openshift/e2e-tests.sh, openshift/knative-eventing.yaml
=> Run tests by using serverless operator

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java
=> [release-v1.3] Handle committing offsets on revoked partitions (#2183)

openshift/e2e-common.sh
=> [release-v1.3] Switch back to use SO main branch

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/AsyncCloseable.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/ResourcesReconciler.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImpl.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandler.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourceReconcilerTestRunner.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandlerTest.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerDeployerVerticle.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerDeployerVerticleTest.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStoreTest.java, openshift/e2e-common.sh, test/channel-e2e-tests.sh, test/scripts/first-event-delay.sh
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2300/files
=> [release-v1.2] Dispatcher verticles are now worker verticles 

control-plane/pkg/reconciler/broker/broker.go
Combination of these two PRs for 1.3
* https://github.com/openshift-knative/eventing-kafka-broker/pull/266
* https://github.com/openshift-knative/eventing-kafka-broker/pull/301
=> [release-v1.3] External topic backport ocp

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
=> Remove vertx circuit breaker

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml, openshift/e2e-tests.sh, openshift/release/artifacts/eventing-kafka-controller.yaml
Cherry-pick of https://github.com/openshift-knative/eventing-kafka-broker/commit/aeee47f5983128437ffb47958910d88d4371b2a1
=> [release-v1.3] Channel services cluster role (#230)

control-plane/pkg/reconciler/channel/channel_test.go
This test is failing locally, on the IDE... :thinking:
=> [release-v1.2] moving a few more over to host-based routing

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/testing/objects_broker.go, openshift/release/artifacts/eventing-kafka-controller.yaml
backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2346
=> [release-v1.2] Adding secret finalizer

openshift/ci-operator/knative-images/dispatcher/Dockerfile, openshift/ci-operator/knative-images/receiver/Dockerfile
making the build a bit closer to downstream
=> [release-v1.2] Using Java RT image

control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/testing/objects_broker.go, openshift/release/artifacts/eventing-kafka-controller.yaml
Like https://github.com/openshift-knative/eventing-kafka-broker/pull/315 but for 1.3
=> [release-v1.3] Backport secret finalizer 1.3

openshift/release/generate-release.sh
Adding script hook, like from #322 to the base/stash location
=> [main] Adding hook for  manifest that has everything in it

openshift/ci-operator/Dockerfile.in, openshift/ci-operator/knative-images/kafka-controller/Dockerfile, openshift/ci-operator/knative-images/post-install/Dockerfile, openshift/ci-operator/knative-images/webhook-kafka/Dockerfile, openshift/ci-operator/knative-test-images/committed-offset/Dockerfile, openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile, openshift/ci-operator/knative-test-images/event-flaker/Dockerfile, openshift/ci-operator/knative-test-images/event-library/Dockerfile, openshift/ci-operator/knative-test-images/event-sender/Dockerfile, openshift/ci-operator/knative-test-images/heartbeats/Dockerfile, openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile, openshift/ci-operator/knative-test-images/partitions-replication-verifier/Dockerfile, openshift/ci-operator/knative-test-images/performance/Dockerfile, openshift/ci-operator/knative-test-images/print/Dockerfile, openshift/ci-operator/knative-test-images/recordevents/Dockerfile, openshift/ci-operator/knative-test-images/request-sender/Dockerfile, openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile, openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile, openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile, openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
Cherry pick of https://github.com/openshift-knative/eventing-kafka-broker/pull/334/
=> [release-v1.1] Self contained dockerfiles for images

openshift/ci-operator/Dockerfile.in, openshift/ci-operator/knative-images/kafka-controller/Dockerfile, openshift/ci-operator/knative-images/webhook-kafka/Dockerfile, openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile, openshift/ci-operator/knative-test-images/event-flaker/Dockerfile, openshift/ci-operator/knative-test-images/event-library/Dockerfile, openshift/ci-operator/knative-test-images/event-sender/Dockerfile, openshift/ci-operator/knative-test-images/heartbeats/Dockerfile, openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile, openshift/ci-operator/knative-test-images/partitions-replication-verifier/Dockerfile, openshift/ci-operator/knative-test-images/performance/Dockerfile, openshift/ci-operator/knative-test-images/print/Dockerfile, openshift/ci-operator/knative-test-images/recordevents/Dockerfile, openshift/ci-operator/knative-test-images/request-sender/Dockerfile, openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile, openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile, openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile, openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
Cherry-pick of https://github.com/openshift-knative/eventing-kafka-broker/pull/334
=> [release-v1.0] Self contained dockerfiles for images

openshift/release/update-to-head.sh
=> [main] Remove mirror upstream branches for now

openshift/patches/override-min-version.patch
=> [main] Update override min k8s version patch

control-plane/config/post-install/500-storage-version-migrator.yaml, openshift/release/artifacts/eventing-kafka-post-install.yaml, openshift/release/artifacts/eventing-kafka.yaml
=> [release-v1.3] looks like wrong storage version migrator was used

openshift/e2e-common.sh
Adjust for 
- https://github.com/knative-sandbox/eventing-kafka-broker/pull/2435
- https://github.com/knative-sandbox/eventing-kafka-broker/pull/2442
=> Adjust midstream for test restructuring

data-plane/config/broker/100-config-kafka-broker-data-plane.yaml, data-plane/config/channel/100-config-kafka-channel-data-plane.yaml, data-plane/config/source/100-config-kafka-source-data-plane.yaml
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/bde3587b582dce06881cdf328561c99c4eca3df4
=> [release-v1.4] Increase default HTTP client max pool size (#2441)

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/a370abc70df0dd788b926adfb587111169c2dc14
=> [release-v1.4] Add pause/resume lifecyecle to ordered consumer (#2438)

openshift/e2e-common.sh
=> [main] Update installation for serverless

data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStore.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStoreTest.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/7ff9bd142b03cf96cf04ce238f67c90a5bef08ed
=> [release-v1.4] Ignore trailing slashes for path-based routing (#2462)

openshift/release/generate-release.sh
Part of https://github.com/openshift-knative/eventing-kafka-broker/pull/368 (aka release-next setup)
=> [main] Include internal CRDs

openshift/patches/use_quay_images.patch
=> [main] Use quay images instead of ko

openshift/release/update-to-head.sh
=> Apply all patches on update to head

openshift/patches/use_quay_images.patch
=> [main] Remove ko usage

openshift/ci-operator/generate-dockerfiles.sh
=> [main] Generate build-image Go version

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2533
=> [release-v1.4] Better handle error response

control-plane/pkg/reconciler/base/reconciler.go, control-plane/pkg/reconciler/base/reconciler_test.go, control-plane/pkg/reconciler/testing/objects_broker.go, control-plane/pkg/reconciler/testing/objects_channel.go, control-plane/pkg/reconciler/testing/objects_sink.go, control-plane/pkg/reconciler/testing/objects_source.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2523
=> [release-v1.4] `pod.Status.Phase == apiv1.PodRunning` is not a good way to test if pods are Running

control-plane/pkg/reconciler/broker/broker.go
Bringing two cherry pick refactors to our midstream, since they are base for future refactors and bug fixes:
* #2575 
* #2576
=> Refactoring cherry picks ocp

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go
:cherries: Cherry pick of #2583 from upstream
=> [release-v1.4] Reword misleading error message

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
Fixes #SRVKE-1292 
backport from upstream to midstream
=> [release-1.4] Doing base 64 encoding of the knative error data

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/testing/objects_broker.go, test/e2e_new/broker_test.go, test/e2e_new/features/broker_deleted_recreated.go
Backport from upstream #2567 PR to OCP
=> [release-v1.4] Checking if received config has data or not

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/controller.go, test/e2e_new/broker_test.go, test/e2e_new/features/broker_deleted_recreated.go
=> [release-v1.4] Backport off Issue/2569 to ocp

control-plane/pkg/reconciler/broker/broker.go
port of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2638/commits/2ce9936bb61344d2a11d2c0bf3925a180af3d728
=> [release-v1.4] Do not copy locks

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/IngressReconcilerListener.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/metrics/MetricsTest.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/IngressRequestHandler.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImpl.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/5370d2922b6384c8b677f1d4c8e529dd5de5f2d0
=> [release-v1.4] Remove meters of deleted resources (#2633)

control-plane/cmd/webhook-kafka/main.go, control-plane/pkg/apis/eventing/v1/broker_validation.go, control-plane/pkg/apis/eventing/v1/broker_validation_test.go
Backport https://github.com/knative-sandbox/eventing-kafka-broker/pull/2626
=> [1.4] Proper webhook backport

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
Backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2657
=> [release-v1.4] Custom error extension prefix 

data-plane/config/broker/500-dispatcher.yaml, data-plane/config/broker/500-receiver.yaml, data-plane/config/brokerv2/500-dispatcher.yaml, data-plane/config/channel/500-dispatcher.yaml, data-plane/config/channel/500-receiver.yaml, data-plane/config/channelv2/500-dispatcher.yaml, data-plane/config/sink/500-receiver.yaml, data-plane/config/source/500-dispatcher.yaml, data-plane/config/sourcev2/500-dispatcher.yaml, openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-channel.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml, openshift/release/artifacts/eventing-kafka-source.yaml, openshift/release/artifacts/eventing-kafka.yaml
=> Fips skip 1.4 ocp part2

control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml, data-plane/config/broker/500-dispatcher.yaml, data-plane/config/broker/500-receiver.yaml, data-plane/config/channel/500-dispatcher.yaml, data-plane/config/channel/500-receiver.yaml, data-plane/config/sink/500-receiver.yaml, data-plane/config/source/500-dispatcher.yaml, openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-channel.yaml, openshift/release/artifacts/eventing-kafka-controller.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml, openshift/release/artifacts/eventing-kafka-source.yaml, openshift/release/artifacts/eventing-kafka.yaml
=> [release-v1.4] Add resource requests for every workload

openshift/e2e-common.sh
=> [release-v1.4] Use matching SO version for testing

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
It's here that we check for retry-able status codes.
=> Fix misleading log message (#2684)

openshift/patches/disable-ko-publish-rekt.patch
=> Fix ko publish rekt patch

openshift/e2e-common.sh
=> Fix missing env var in tests

openshift/ci-operator/build-image/Dockerfile
=> Remove -mod=vendor from GOFLAGS when installing yq

openshift/ci-operator/generate-dockerfiles.sh
=> Replace base Go image based on go.mod

control-plane/config/eventing-kafka-broker/200-webhook/400-webhook-pod-defaulting.yaml, openshift/release/artifacts/eventing-kafka-controller.yaml, openshift/release/artifacts/eventing-kafka.yaml, openshift/release/generate-release.sh
See https://github.com/openshift-knative/serverless-operator/pull/1755 and
https://issues.redhat.com/browse/SRVKE-1324 for more details.
=> [SRVKE-1324] Remove matchExpression from webhook definition

control-plane/pkg/kafka/topic.go, control-plane/pkg/reconciler/channel/channel_test.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/f4b9b1ebfc3a62017591d1828783af92b595ef09
=> [release-v1.5] Use full TopicDetail when creating new topics (#2700)

openshift/patches/override-min-version.patch
=> Update min version patch for release-next

openshift/ci-operator/build-image/Dockerfile, openshift/ci-operator/generate-dockerfiles.sh
=> Set base build image based on go.mod

openshift/knative-eventing.yaml
See individual commits for details.
=> [main] Update eventing installation with tracing and timeout feature enabled

openshift/release/create-release-branch.sh
=> [main] Apply patches when creating release branches

openshift/release/generate-release.sh, openshift/release/resolve.sh
=> [main] Resolve images using tags instead of image streams

openshift/patches/security-context-for-test-pods.patch, openshift/release/generate-release.sh, vendor/knative.dev/pkg/test/security/security.go, vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml, vendor/knative.dev/reconciler-test/pkg/eventshub/resources.go, vendor/knative.dev/reconciler-test/pkg/k8s/pod.go, vendor/knative.dev/reconciler-test/pkg/manifest/options.go
=>  [release-v1.4] Allow running rekt tests in namespace with enforced "restricted" pod

OWNERS
As per eventing onboarding: Adding myself to the OWNERS file
=> Add creydr to OWNERS

openshift/e2e-common.sh, openshift/e2e-conformance-tests.sh, openshift/e2e-rekt-tests.sh, openshift/e2e-tests.sh
=> [release-v1.6] Remove unused test code

openshift/e2e-common.sh
=> [release-v1.5] Clone matching SO repository branch

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentialsTest.java, test/e2e_sink/kafka_sink_test.go, test/kafka/kafka-ephemeral.yaml, test/pkg/run.go, test/pkg/testing/auth.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2790
Jira: https://issues.redhat.com/browse/SRVKE-1328
=> [release-v1.6] Fix KubernetesCredentials skip.user decoding

Makefile
* Build also vendored images rather than depending on a specific version built by Eventing or reconciler-test. Keeping versions of vendored images in sync with what is needed by eventing-kafka-broker is complicated. And image template for tests would be more complex as well.
* Use "ko build" for images that do not have yaml files and "ko resolve" (as a backup) for images that do not have Go source files and only have yamls.
=> [release-v1.5] Build also vendored test images for multiarch

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentials.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesCredentialsTest.java, test/e2e/kafka_sink_test.go, test/kafka/kafka-ephemeral.yaml, test/pkg/testing/auth.go, test/pkg/testing/run.go
Manual cherry-pick of #472 with solved merge conflicts
=> [release-v1.5] Fix KubernetesCredentials skip.user decoding

openshift/knative-eventing.yaml
=> [release-v1.6] Migrate KnativeEventing to v1beta1

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSenderTest.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/3d84363ad294356f15717d6585e1f7b2ed403fec
=> [release-v1.6] Retry Only If the Status Code Is Retryable (#2798)

Makefile
* Build also vendored images rather than depending on a specific version built by Eventing or reconciler-test. Keeping versions of vendored images in sync with what is needed by eventing-kafka-broker is complicated. And image template for tests would be more complex as well.
* Use "ko build" for images that do not have yaml files and "ko resolve" (as a backup) for images that do not have Go source files and only have yamls.
=> Build also vendored test images for multiarch

control-plane/pkg/apis/core/pod_defaulting.go, control-plane/pkg/apis/internals/kafka/eventing/data_plane.go, control-plane/pkg/reconciler/base/reconciler.go, control-plane/pkg/reconciler/consumer/consumer.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/consumergroup/controller.go, control-plane/pkg/reconciler/consumergroup/controller_test.go, control-plane/pkg/reconciler/testing/objects_common.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/edd57af0448822e6fe12de23bbed373012467814
=> [release-v1.6] Create contract ConfigMaps in ConsumerGroup reconciler (#2773)

control-plane/pkg/kafka/testing/admin_mock.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/testing/errors.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2816/files
=> [release-v1.6] Handle ConsumerGroup finalization for deleted topics

control-plane/pkg/reconciler/broker/broker_test.go, control-plane/pkg/reconciler/broker/namespaced_broker_test.go, control-plane/pkg/reconciler/testing/listers.go, control-plane/pkg/reconciler/testing/objects_broker.go, control-plane/pkg/reconciler/testing/objects_common.go, control-plane/pkg/reconciler/testing/objects_consumergroup.go, vendor/github.com/manifestival/manifestival/fake/client.go, vendor/modules.txt
Cherry pick https://github.com/knative-sandbox/eventing-kafka-broker/pull/2817
=> [release 1.6] Missing unit tests for namespaced broker (#2817)

openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-channel.yaml, openshift/release/artifacts/eventing-kafka-controller.yaml, openshift/release/artifacts/eventing-kafka-post-install.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml, openshift/release/artifacts/eventing-kafka-source.yaml, openshift/release/artifacts/eventing-kafka.yaml, vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml, vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml, vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml, vendor/knative.dev/eventing/test/test_images/event-sender/pod.yaml, vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml, vendor/knative.dev/eventing/test/test_images/performance/pod.yaml, vendor/knative.dev/eventing/test/test_images/print/pod.yaml, vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml, vendor/knative.dev/eventing/test/test_images/request-sender/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-fetcher/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-forwarder/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-receiver/pod.yaml, vendor/knative.dev/eventing/test/test_images/wathola-sender/pod.yaml, vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
/hold
This is the result of `make RELEASE=v1.7 generate-release` against the `release-v1.7` branch, which was manually created out of our 1.6 branch
=> [release-v1.7] Run make release 1.7

control-plane/pkg/propagator/resource_propagator.go, control-plane/pkg/propagator/resource_propagator_test.go, control-plane/pkg/reconciler/broker/namespaced_broker.go, go.mod, test/e2e_new/features/featuressteps/broker.go, test/e2e_new/features/namespaced_broker.go
Manual cherry pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2854
=> [1.6] Templating support in namespaced broker additional resources

test/e2e_broker/broker_redelivery_test.go, test/e2e_broker/broker_trigger_test.go, test/e2e_broker/conformance/control_plane_conformance_test.go, test/pkg/broker/broker.go, test/upgrade-tests.sh, test/upgrade/continual.go, test/upgrade/continual/broker.go, test/upgrade/continual/types.go, test/upgrade/postdowngrade.go, test/upgrade/postupgrade.go, test/upgrade/preupgrade.go, test/upgrade/smoke.go, test/upgrade/suite.go
=> [release-v1.6] Namespaced broker upgrade tests (#2741)

data-plane/config/source/500-dispatcher.yaml, openshift/patches/remove_source_limits.patch, openshift/release/artifacts/eventing-kafka-source.yaml, openshift/release/artifacts/eventing-kafka.yaml
Fixes https://issues.redhat.com/browse/SRVKE-1378
=> [SRVKE-1378] Remove kafka-source-dispatcher default limits 

openshift/patches/remove_source_limits.patch
=> [main] Add remove kafka-source-dispatcher default limits patch

control-plane/pkg/counter/counter.go, control-plane/pkg/counter/counter_test.go, control-plane/pkg/prober/cache.go, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/broker/namespaced_broker.go, control-plane/pkg/reconciler/broker/namespaced_controller.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/consumergroup/controller.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2872/files
=> [release-v1.6] Improve ConsumerGroup finalization for missing resources

control-plane/pkg/prober/cache.go, control-plane/pkg/prober/prober.go, control-plane/pkg/reconciler/broker/broker.go, test/e2e_new/broker_test.go, test/e2e_new/features/namespace.go, test/e2e_new/features/namespaced_broker.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2896/files
=> [release-1.6] Fix delete namespace with a namespaced broker stuck on finalizer (#2896)

openshift/e2e-common.sh
=> [release-v1.7] Add a function to run Kafka Broker conformance tests only

control-plane/pkg/reconciler/broker/namespaced_broker.go
Backport https://github.com/knative-sandbox/eventing-kafka-broker/pull/2911
=> [release 1.6] Don't set ownerRefs on cluster scoped resources

control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/broker_test.go
Backport of a few improvements from upstream main to our 1.7 (and soon 1.8 brach)
1. https://github.com/knative-sandbox/eventing-kafka-broker/commit/71778c7500cfeba4204ef8fd03c014fc151f1b67
2. https://github.com/knative-sandbox/eventing-kafka-broker/commit/f9f5345e92d07c99295e9bbf5dbcdad09e95f155
3. https://github.com/knative-sandbox/eventing-kafka-broker/commit/34d3f2deaf74f3d6de6b958fbf1f043e53bebb26
4. https://github.com/knative-sandbox/eventing-kafka-broker/commit/2f8ffc6b069e1f901c7d11cefd2c6d1cad8e6ecc
5. https://github.com/knative-sandbox/eventing-kafka-broker/commit/e0ec3ade79c503042ff749508d3a24473827314f
=> [release-v1.7 ] Several backports from upstream main for our midstream

data-plane/config/source/500-dispatcher.yaml, openshift/patches/remove_source_limits.patch, openshift/release/artifacts/eventing-kafka-source.yaml, openshift/release/artifacts/eventing-kafka.yaml
Remove
```
-XX:InitialRAMPercentage=70.0 -XX:MinRAMPercentage=70.0 -XX:MaxRAMPercentage=70.0
```
since now we don't have container limits set
=> [release-v1.6] [SRVKE-1392] Update remove_source_limits.patch 

control-plane/pkg/reconciler/base/reconciler.go, control-plane/pkg/reconciler/broker/namespaced_broker_test.go, control-plane/pkg/reconciler/consumer/consumer_test.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2924
=> [release-v1.6] Enforce owner references on contract ConfigMap creation

control-plane/pkg/reconciler/consumergroup/controller.go
Backport for upstream issue https://github.com/knative-sandbox/eventing-kafka-broker/issues/2926
=> [release-v1.7] Perform type assertion on conversion

control-plane/pkg/reconciler/consumergroup/controller.go
Manual cherry-pick :cherries:  of https://github.com/openshift-knative/eventing-kafka-broker/pull/569
=> [release-v1.6] Perform type assertion on conversion

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_lifecycle.go, control-plane/pkg/reconciler/consumergroup/auth.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/consumergroup/controller.go, control-plane/pkg/reconciler/consumergroup/evictor.go, control-plane/pkg/reconciler/testing/objects_common.go, go.mod, openshift/patches/fix_scheduler_and_autoscaler.patch, openshift/release/generate-release.sh, vendor/knative.dev/eventing/pkg/scheduler/state/helpers.go, vendor/knative.dev/eventing/pkg/scheduler/state/state.go, vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go, vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
=> [release-v1.6] [SRVKE-1400] Measure initialize offsets and schedule latency, move to use max fill up for scheduler

openshift/ci-operator/Dockerfile.in, openshift/ci-operator/knative-images/kafka-controller/Dockerfile, openshift/ci-operator/knative-images/post-install/Dockerfile, openshift/ci-operator/knative-images/webhook-kafka/Dockerfile, openshift/ci-operator/knative-test-images/committed-offset/Dockerfile, openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile, openshift/ci-operator/knative-test-images/event-flaker/Dockerfile, openshift/ci-operator/knative-test-images/event-library/Dockerfile, openshift/ci-operator/knative-test-images/event-sender/Dockerfile, openshift/ci-operator/knative-test-images/eventshub/Dockerfile, openshift/ci-operator/knative-test-images/heartbeats/Dockerfile, openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile, openshift/ci-operator/knative-test-images/partitions-replication-verifier/Dockerfile, openshift/ci-operator/knative-test-images/performance/Dockerfile, openshift/ci-operator/knative-test-images/print/Dockerfile, openshift/ci-operator/knative-test-images/recordevents/Dockerfile, openshift/ci-operator/knative-test-images/request-sender/Dockerfile, openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile, openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile, openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile, openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
Similar to this: https://github.com/openshift-knative/eventing/pull/117
=> [release-v1.7] Ubi8 for midstream

data-plane/config/broker/500-receiver.yaml, data-plane/config/channel/500-receiver.yaml, data-plane/config/sink/500-receiver.yaml, openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-channel.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml, openshift/release/artifacts/eventing-kafka.yaml
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2950 for [SRVKE-1409](https://issues.redhat.com/browse/SRVKE-1409)
* Increase kafka-broker-receivers memory requests
* Increase kafka-channel-receiver memory requests
* Increase kafka-sink-receiver memory requests
=> [release-1.7] SRVKE-1409: Increase receivers memory request

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerMessageHandler.java
Data plane reconciliation might fail for many reasons, especially when using Istio with EKB and namespaced broker that creates data plane automatically when a broker is created the first reconciliation on startup often fails since istio proxy might not have started yet.
=> [release-v1.7] Retry failed reconciliations on the data plane (#3009)

data-plane/config/source/500-dispatcher.yaml, openshift/patches/remove_ram_percentage.patch, openshift/release/artifacts/eventing-kafka-source.yaml, openshift/release/artifacts/eventing-kafka.yaml
We don't set limits, so we can't define percentages.
=> [release-v1.9] Remove JVM RAM percentage

openshift/patches/remove_ram_percentage.patch
Cherry-pick of https://github.com/openshift-knative/eventing-kafka-broker/pull/699
=> [main] Add patch: remove RAM percentage

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManager.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OffsetManagerTest.java
Backport from upstream 3103 to OCP
> Before this patch, we were caching the new offset before committing to Kafka the offset, causing the offset to not be stored until a new record is successfully processed.
=> [release-v1.9] Retry offset commit (#3103)

control-plane/pkg/reconciler/source/source.go, control-plane/pkg/reconciler/source/source_test.go
- Cherry pick commit https://github.com/knative-sandbox/eventing-kafka-broker/commit/e45c5fec51f1e4af193afdede8efa10d780b0fae to version 1.8
=> Cherry pick sourcev2 upgrade fix to v1.8

openshift/patches/maxfillup_scheduler.patch
https://github.com/openshift-knative/eventing-kafka-broker/pull/716 but for main
=> [main] Use MAXFILLUP scheduler

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/http/WebClientCloudEventSender.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/fe4652b827a0110442d813a737559f156b7709cd
=> [release-v1.9] Send namespace header in MT components (#3184)

openshift/release/create-release-branch.sh
Similar to https://github.com/openshift-knative/eventing/pull/281
=> [main] Use target/midstream branch instead of upstream tag to infer tag

openshift/patches/add-eventshub-port-name.patch, openshift/release/generate-release.sh, vendor/knative.dev/reconciler-test/pkg/eventshub/102-service.yaml
Similar to https://github.com/openshift-knative/eventing/pull/289
=> [release-v1.9] Add eventshub service port name

go.mod, openshift/ci-operator/build-image/Dockerfile
Run `make generate-release` using openshift-knative/hack.
=> [release-v1.10] Run `make generate-release`

openshift/ci-operator/build-image/Dockerfile
Run `make generate-release` using openshift-knative/hack.
=> [release-v1.9] Run `make generate-release`

hack/update-checksums.sh, openshift/ci-operator/build-image/Dockerfile, openshift/patches/remove-hash-gen-config-tracing.patch
=> [release-v1.11] Remove hash-gen for config-tracing since it doesn't exist 

control-plane/pkg/reconciler/channel/channel.go
=> [release-v1.10] Fix channel finalizer logic (#3295)

.ko.yaml, control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml, control-plane/config/eventing-kafka-broker/200-webhook/500-webhook.yaml, control-plane/config/eventing-kafka-source/200-controller/500-controller.yaml, control-plane/config/post-install/500-post-install-job.yaml, control-plane/config/post-install/500-storage-version-migrator.yaml, control-plane/pkg/reconciler/consumergroup/controller.go, data-plane/config/broker/500-dispatcher.yaml, data-plane/config/broker/500-receiver.yaml, data-plane/config/brokerv2/500-dispatcher.yaml, data-plane/config/channel/500-dispatcher.yaml, data-plane/config/channel/500-receiver.yaml, data-plane/config/channelv2/500-dispatcher.yaml, data-plane/config/sink/500-receiver.yaml, data-plane/config/source/500-dispatcher.yaml, test/e2e_new/broker_test.go, test/e2e_source/helpers/kafka_helper.go, test/scripts/first-event-delay.sh, test/upgrade/postupgrade.go, vendor/knative.dev/reconciler-test/pkg/images/ko/publish.go
Patches were not committed, fixed by: https://github.com/openshift-knative/eventing-kafka-broker/pull/805
=> [release-v1.11] Apply patches

control-plane/pkg/reconciler/base/reconciler.go, control-plane/pkg/reconciler/base/reconciler_test.go
Backport of https://github.com/knative-extensions/eventing-kafka-broker/pull/3335
=> [release-v1.9] Ignore unknown fields in data plane contract (#3335)

control-plane/pkg/reconciler/base/reconciler.go, control-plane/pkg/reconciler/base/reconciler_test.go
Backport of https://github.com/knative-extensions/eventing-kafka-broker/pull/3335
=> [release-v1.10] Ignore unknown fields in data plane contract (#3335)

openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-channel.yaml, openshift/release/artifacts/eventing-kafka-controller.yaml, openshift/release/artifacts/eventing-kafka-post-install.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml, openshift/release/artifacts/eventing-kafka-source.yaml, openshift/release/artifacts/eventing-kafka-tls-networking.yaml, openshift/release/artifacts/eventing-kafka.yaml, openshift/release/generate-release.sh, openshift/release/resolve.sh
Similar to https://github.com/openshift-knative/eventing/pull/369 but for EKB
+ some label fixes
=> [release-v1.11] Create `eventing-kafka-tls-networking.yaml` artifact

data-plane/pom.xml
(see their 'c2fa0343cb71ae7641b78862ca0767b2d3b8d888' )
=> [release-v1.10] Align version override with the Quarkus team

data-plane/pom.xml
=> [release-v1.11] updating to latest Quarkus 3.2.x version

data-plane/config/broker-tls/broker-ingress-tls-certificate.yaml, data-plane/config/channel-tls/channel-ingress-tls-certificate.yaml, data-plane/config/sink-tls/sink-ingress-tls-certificate.yaml, openshift/release/artifacts/eventing-kafka-tls-networking.yaml
Cherry-pick of https://github.com/knative-extensions/eventing-kafka-broker/commit/662b268370efd7d896a78e05ac6f1429528f3009
=> [release-v1.11] Add the kafka-xyz.knative-eventing.svc as hostname (#3306)

data-plane/config/broker-tls/broker-ingress-tls-certificate.yaml, data-plane/config/channel-tls/channel-ingress-tls-certificate.yaml, data-plane/config/sink-tls/sink-ingress-tls-certificate.yaml, openshift/release/artifacts/eventing-kafka-tls-networking.yaml
CP of https://github.com/knative-extensions/eventing-kafka-broker/commit/e7017efef281a046280e27da77d05101632b3d53
=> [release-v1.11] Workaround for cert-manager update spec issue (#3390) 

openshift/release/generate-release.sh
Adding missing patch to "patch list"
=> [release-v1.10] Update patch list

openshift/release/generate-release.sh
=> [release-v1.9] Update patch list

openshift/release/generate-release.sh
Adding missing patch to "patch list"
=> [release-v1.11] Update patch list 

openshift/e2e-common.sh
=> [release-1.10] use release-1.31 branch for S-O

openshift/patches/chmod-codegen.patch, openshift/release/generate-release.sh, vendor/knative.dev/hack/codegen-library.sh
Plus applying the patch.
This aims to backport changes from upstream.
=> [release-v1.11] Patch for chmod on codegen files

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_lifecycle.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/testing/objects_consumergroup.go
Cherry pick of https://github.com/knative-extensions/eventing-kafka-broker/commit/999150274bb5d73ee7634672a60131ce3c85bb3c
=> [release-v1.11] Update ConsumerGroup status on finalization for better error reporting (#3415)

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisher.java
Cherry pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/3486
=> [release-v1.12] ignore unknown fields in data plane contract (#3486)

control-plane/pkg/autoscaler/config.go, control-plane/pkg/autoscaler/keda/keda.go
Cherry pick of the KEDA kafka source fix from upstream
/cc @pierDipi
=> [release-v1.12] Remove activationLagThreshold to fix 0->1 scaling (#3479)

control-plane/pkg/reconciler/broker/namespaced_broker.go, openshift/patches/namespaced_broker_copy_trustedca_cm.patch
patch the ns broker pod, and have the trusted bundle CM join the copy party
=> [release-v1.11] Apply cm copy over 1.11

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventbus/ContractPublisher.java
Cherry pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/3486
=> [release-v1.11] ignore unknown fields in data plane contract (#3486)

test/e2e_new/broker_config_test.go
backport https://github.com/knative-extensions/eventing-kafka-broker/pull/3593
=> [release-v1.11] skip TestBrokerWithConfig

go.mod, go.sum, openshift/ci-operator/build-image/Dockerfile, openshift/ci-operator/knative-images/event_display/Dockerfile, openshift/ci-operator/knative-images/heartbeats/Dockerfile, openshift/ci-operator/knative-images/kafka-controller/Dockerfile, openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile, openshift/ci-operator/knative-images/migrate/Dockerfile, openshift/ci-operator/knative-images/post-install/Dockerfile, openshift/ci-operator/knative-images/webhook-kafka/Dockerfile, openshift/ci-operator/knative-test-images/committed-offset/Dockerfile, openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile, openshift/ci-operator/knative-test-images/event-sender/Dockerfile, openshift/ci-operator/knative-test-images/eventshub/Dockerfile, openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile, openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile, openshift/ci-operator/knative-test-images/performance/Dockerfile, openshift/ci-operator/knative-test-images/print/Dockerfile, openshift/ci-operator/knative-test-images/recordevents/Dockerfile, openshift/ci-operator/knative-test-images/request-sender/Dockerfile, openshift/ci-operator/knative-test-images/watch-cm/Dockerfile, openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile, openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile, openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile, openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile, openshift/release/artifacts/eventing-kafka-broker.yaml, openshift/release/artifacts/eventing-kafka-controller.yaml, openshift/release/artifacts/eventing-kafka-sink.yaml, openshift/release/artifacts/eventing-kafka.yaml
Related to https://github.com/openshift-knative/serverless-operator/pull/2451
=> [release-v1.11] Bump to Go v1.21

Makefile, openshift/e2e-common.sh
This is an attempt at adding a makefile target for the keda tests.
=> [release-v1.11] Add makefile target for kafka keda tests

go.mod, go.sum, vendor/knative.dev/reconciler-test/pkg/eventshub/assert/step.go, vendor/modules.txt
to get https://github.com/knative-extensions/reconciler-test/pull/665 in 1.11
=> [release-v1.11] update reconciler-test to current release-1.11

control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/testing/objects_consumergroup.go
=> [release-v1.11] Fix selector path for cg scale subresource (#3666)

Makefile, openshift/e2e-common.sh, openshift/e2e-rekt-encryption-auth-tests.sh, openshift/knative-eventing-encryption-auth.yaml
Manual cherry-pick of https://github.com/openshift-knative/eventing-kafka-broker/pull/990 as automatic failed: https://github.com/openshift-knative/eventing-kafka-broker/pull/990#issuecomment-1953665606
/cc @pierDipi
=> [release-1.13] Add KEDA and TLS tests

control-plane/pkg/core/config/utils.go, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/consumer/consumer.go, control-plane/pkg/reconciler/sink/kafka_sink.go
Backport of https://github.com/knative-extensions/eventing-kafka-broker/pull/3723
=> [release-v1.11] Detect trust bundles changes

go.mod, go.sum, vendor/modules.txt
same PR as #3754 from upstream
=> [release-v1.13] Unpin CE Kafka protocol version from older version

openshift/patches/remove_broker_dispatcher_limits.patch, openshift/patches/remove_seccomp_profile.patch
- Add remove limits similar to https://github.com/openshift-knative/eventing-kafka-broker/blob/main/openshift/patches/remove_source_limits.patch
- Fix openshift/patches/remove_seccomp_profile.patch
=> Fix patches for trigger v2

openshift/e2e-common.sh
=> Add OIDC tests to encryption/auth test suite

control-plane/pkg/reconciler/consumergroup/evictor.go, control-plane/pkg/reconciler/consumergroup/evictor_test.go, data-plane/receiver-loom/src/main/java/dev/knative/eventing/kafka/broker/receiverloom/LoomKafkaProducer.java
Cherry-picks:
- https://github.com/openshift-knative/eventing-kafka-broker/commit/2d15a0bc10af56bc30fb36f362ac57ff5e574a5b
- https://github.com/openshift-knative/eventing-kafka-broker/commit/08ab7fec3df92581a93404c02bce2203363df513
=> [release-v1.12] Fix evictor panic and IllegalStateException: Result is already complete

go.mod, go.sum, vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go, vendor/modules.txt
Updating reconciler test to include https://github.com/knative-extensions/reconciler-test/pull/713/files
=> [release-v1.12] updated reconciler test

go.mod, go.sum, openshift/release/artifacts/eventing-kafka-controller.yaml, openshift/release/artifacts/eventing-kafka.yaml, vendor/knative.dev/reconciler-test/pkg/eventshub/forwarder/forwarder.go, vendor/modules.txt
Update reconciler-test to include the fixes in https://github.com/knative-extensions/reconciler-test/pull/713/files
=> [release-v1.14]: update rekt

data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/OrderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java, data-plane/profiler/resources/config-logging.xml, data-plane/profiler/run.sh, data-plane/receiver-loom/src/main/java/dev/knative/eventing/kafka/broker/receiverloom/LoomKafkaProducer.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
CP of https://github.com/knative-extensions/eventing-kafka-broker/commit/661976a0b5566bed92f3b598941c94f16408a9bd
=> [release-v1.12] Introduce a `ENABLE_VIRTUAL_THREADS` env variable to enable virtual threads, default to real threads for now (#3882)

openshift/patches/refactor_newfilters.patch, openshift/release/generate-release.sh, test/e2e_new/new_trigger_filters_test.go, vendor/knative.dev/eventing/test/rekt/features/new_trigger_filters/feature.go, vendor/knative.dev/eventing/test/rekt/features/new_trigger_filters/filters.go, vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
Same as https://github.com/openshift-knative/eventing-kafka-broker/pull/1085, only for release-v1.14 branch.
=> [release-1.14] Refactor NewFiltersFeatureSet to prevent starvation

openshift/patches/refactor_newfilters.patch, openshift/release/generate-release.sh, test/e2e_new/new_trigger_filters_test.go, vendor/knative.dev/eventing/test/rekt/features/new_trigger_filters/feature.go, vendor/knative.dev/eventing/test/rekt/features/new_trigger_filters/filters.go, vendor/knative.dev/eventing/test/rekt/resources/broker/broker.go
=> [release-1.12] Refactor NewFiltersFeatureSet to prevent starvation

openshift/patches/remove_dispatcher_limits.patch
=> Add patch to remove limits from kafka broker dispatcher

control-plane/cmd/post-install/kafka_namespaced_broker_deployment_deleter.go, control-plane/config/post-install/200-controller-cluster-role.yaml, openshift/release/artifacts/eventing-kafka-post-install.yaml, openshift/release/artifacts/eventing-kafka.yaml
Backport for https://github.com/knative-extensions/eventing-kafka-broker/commit/2571f20613e7e0d08fd66ad78b4b6268f87489d0
=> [release-v1.14] Add post install logic for namespaced brokers (#3889)

control-plane/cmd/webhook-kafka/main.go, control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation_test.go
backport to midstream from upstream (#3924)
=> [release-v1.14] Allow different namespace references

openshift/patches/remove_channel_dispatcher_limits.patch
Same as #1105 except for `main`
=> add patch to remove channel dispatcher limits

data-plane/THIRD-PARTY.txt, data-plane/pom.xml
=> [release-v.14] Downgrade slf4j-api to 1.7.x to fix logging issues

openshift/generate.sh
To fix https://master-jenkins-csb-serverless-qe.apps.ocp-c1.prod.psi.redhat.com/job/ci/job/knative-nightly-ci-eventing-kafka-broker/734/console
=> Clone hack repo to install generate

openshift/patches/trigger_tests_set_annotations_correctly_now.patch, openshift/release/generate-release.sh, vendor/knative.dev/eventing/test/rekt/features/trigger/feature.go, vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.go, vendor/knative.dev/eventing/test/rekt/resources/trigger/trigger.yaml
backport from https://github.com/knative/eventing/pull/7887  
adding as a vendor patch
=> [release-v1.14] backport trigger_tests_set_annotations_correctly_now patch

openshift/patches/rekt-serviceaccounts-delete.patch, openshift/release/generate-release.sh
Bring the patch from https://github.com/openshift-knative/eventing-kafka-broker/pull/1125 to main branch.
=> Patch for deleting service accounts

openshift/patches/rekt-serviceaccounts-delete.patch, openshift/release/generate-release.sh, vendor/knative.dev/reconciler-test/pkg/feature/feature.go
Similar to https://github.com/openshift-knative/serverless-operator/pull/2733
=> Workaround for OCPBUGS-35731 Repeat deleting service accounts

control-plane/pkg/kafka/clientpool/clientpool.go, control-plane/pkg/kafka/clientpool/clientpool_test.go, control-plane/pkg/kafka/clientpool/clusteradmin.go, control-plane/pkg/kafka/testing/admin_mock.go, control-plane/pkg/kafka/testing/client_mock.go, control-plane/pkg/security/secrets_provider_net_spec.go, control-plane/pkg/security/secrets_provider_net_spec_test.go
This PR backports https://github.com/knative-extensions/eventing-kafka-broker/pull/4001 and https://github.com/knative-extensions/eventing-kafka-broker/pull/4005 to fix issues with kafka connection pooling
=> [release-v1.14] Clientpool fixes

data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreator.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreatorImpl.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeListerFactory.java, data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/eventtype/EventTypeCreatorImplTest.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/IngressProducer.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStore.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImpl.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStoreTest.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/AuthenticationHandlerTest.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/handler/IngressRequestHandlerImplTest.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java, data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/AbstractDataPlaneTest.java
Cherry-pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/4031
=> [release-v1.14] feat: use namespaced indexers for eventtypes in receiver (#4031)

.konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-dispatcher.yaml, .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-event-display.yaml, .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-heartbeats.yaml, .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-kafka-controller.yaml, .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-migrate.yaml, .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-post-install.yaml, .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-receiver.yaml, .konflux/applications/serverless-operator-release-next/components/openshift-knative-eventing-kafka-broker-release-next-knative-eventing-kafka-broker-webhook-kafka.yaml
Add Konflux components and pipelines
=> [main] Add Konflux configurations

control-plane/pkg/reconciler/trigger/v2/triggerv2.go, control-plane/pkg/reconciler/trigger/v2/triggerv2_test.go
=> [release-v1.14] Remove finalizer when trigger is deleted

control-plane/pkg/contract/contract.pb.go, control-plane/pkg/reconciler/sink/kafka_sink.go, control-plane/pkg/reconciler/sink/kafka_sink_test.go, test/e2e_new/sink_auth_test.go, test/rekt/resources/kafkasink/kafkasink.go, test/rekt/resources/kafkatopic/topic.go
Same as https://github.com/openshift-knative/eventing-kafka-broker/pull/1162 but for 1.14
=> [release-1.14] Expose OIDC audience of KafkaSink in its status

.konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-dispatcher-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-event-display-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-heartbeats-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-kafka-controller-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-migrate-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-post-install-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-receiver-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-committed-offset-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-consumer-group-lag-provider-test-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-event-sender-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-eventshub-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-kafka-consumer-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-logs-exporter-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-print-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-recordevents-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-request-sender-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-watch-cm-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-wathola-fetcher-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-wathola-forwarder-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-wathola-receiver-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-test-wathola-sender-115.yaml, .konflux/applications/serverless-operator-135/components/imagerepositories/kn-ekb-webhook-kafka-115.yaml, .konflux/applications/serverless-operator-135/tests/ec-test.yaml
Add Konflux components and pipelines
=> [release-v1.15] Add Konflux configurations

control-plane/pkg/reconciler/trigger/v2/triggerv2.go, control-plane/pkg/reconciler/trigger/v2/triggerv2_test.go
=> [release-v1.15] Remove finalizer when trigger is deleted

control-plane/config/post-install/200-controller-cluster-role.yaml, openshift/ci-operator/build-image/Dockerfile, openshift/ci-operator/knative-images/event_display/Dockerfile, openshift/ci-operator/knative-images/heartbeats/Dockerfile, openshift/ci-operator/knative-images/kafka-controller/Dockerfile, openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile, openshift/ci-operator/knative-images/migrate/Dockerfile, openshift/ci-operator/knative-images/post-install/Dockerfile, openshift/ci-operator/knative-images/webhook-kafka/Dockerfile, openshift/ci-operator/knative-test-images/committed-offset/Dockerfile, openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile, openshift/ci-operator/knative-test-images/event-sender/Dockerfile, openshift/ci-operator/knative-test-images/eventshub/Dockerfile, openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile, openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile, openshift/ci-operator/knative-test-images/print/Dockerfile, openshift/ci-operator/knative-test-images/recordevents/Dockerfile, openshift/ci-operator/knative-test-images/request-sender/Dockerfile, openshift/ci-operator/knative-test-images/watch-cm/Dockerfile, openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile, openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile, openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile, openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile, openshift/release/artifacts/eventing-kafka-controller.yaml, openshift/release/artifacts/eventing-kafka-post-install.yaml, openshift/release/artifacts/eventing-kafka.yaml
This is a cherry pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/4016 to make sure that post install jobs have the correct permissions in the clusterrole
=> [release-v1.15] fix: correct clusterrole permissions (#4016)

openshift/ci-operator/static-images/dispatcher/Dockerfile, openshift/ci-operator/static-images/receiver/Dockerfile
=> [release-v1.15] Add expected labels to static images

openshift/ci-operator/knative-images/event_display/Dockerfile, openshift/ci-operator/knative-images/heartbeats/Dockerfile, openshift/ci-operator/knative-images/kafka-controller/Dockerfile, openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile, openshift/ci-operator/knative-images/migrate/Dockerfile, openshift/ci-operator/knative-images/post-install/Dockerfile, openshift/ci-operator/knative-images/webhook-kafka/Dockerfile, openshift/ci-operator/knative-test-images/committed-offset/Dockerfile, openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile, openshift/ci-operator/knative-test-images/event-sender/Dockerfile, openshift/ci-operator/knative-test-images/eventshub/Dockerfile, openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile, openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile, openshift/ci-operator/knative-test-images/print/Dockerfile, openshift/ci-operator/knative-test-images/recordevents/Dockerfile, openshift/ci-operator/knative-test-images/request-sender/Dockerfile, openshift/ci-operator/knative-test-images/watch-cm/Dockerfile, openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile, openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile, openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile, openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile, openshift/release/artifacts/eventing-kafka-controller.yaml, openshift/release/artifacts/eventing-kafka.yaml
Run `make generate-release` using openshift-knative/hack.
=> [release-v1.15] Run `make generate-release`

openshift/e2e-common.sh
Port https://github.com/openshift-knative/eventing-kafka-broker/pull/1164 to main
=> [main] Fix e2e tests (#1164)

control-plane/cmd/kafka-controller/main.go, control-plane/config/eventing-kafka-broker/200-controller/500-controller.yaml, control-plane/pkg/kafka/clientpool/clientpool.go, control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/broker/namespaced_controller.go, control-plane/pkg/reconciler/channel/controller.go, control-plane/pkg/reconciler/consumergroup/consumergroup.go, control-plane/pkg/reconciler/consumergroup/consumergroup_test.go, control-plane/pkg/reconciler/consumergroup/controller.go, control-plane/pkg/reconciler/sink/controller.go, control-plane/pkg/reconciler/trigger/controller.go, control-plane/pkg/reconciler/trigger/namespaced_controller.go, go.mod, go.sum, vendor/knative.dev/eventing/pkg/scheduler/scheduler.go, vendor/knative.dev/eventing/pkg/scheduler/state/helpers.go, vendor/knative.dev/eventing/pkg/scheduler/state/state.go, vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go, vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go, vendor/modules.txt
Backport of:
- https://github.com/knative-extensions/eventing-kafka-broker/pull/4108
- https://github.com/knative-extensions/eventing-kafka-broker/pull/4112
=> [release-v1.15] Allow enabling sarama logging and disabling client pool and Upgrade knative.dev/eventing to latest 1.15

openshift/patches/eventing_auth_serviceaccount_creationtimestamp.patch, openshift/release/generate-release.sh, vendor/knative.dev/eventing/pkg/auth/serviceaccount.go
vendoring in https://github.com/openshift-knative/eventing/pull/891
=> [release-v1.14] workaround DeepDerivative CreationTimestamp comparison

control-plane/config/post-install/500-post-install-job.yaml, control-plane/config/post-install/500-storage-version-migrator.yaml, test/config/monitoring.yaml
Ref: https://github.com/knative/eventing/issues/8204
backport
=> [release-v1.15] Use istio inject label

openshift/ci-operator/static-images/dispatcher/Dockerfile, openshift/ci-operator/static-images/dispatcher/hermetic/Dockerfile, openshift/ci-operator/static-images/dispatcher/hermetic/Dockerfile.deps, openshift/ci-operator/static-images/receiver/hermetic/Dockerfile, openshift/ci-operator/static-images/receiver/hermetic/Dockerfile.deps
Port https://github.com/openshift-knative/eventing-kafka-broker/pull/1287 to main
=> [main] Dockerfiles and build changes for hermetic Java builds 

control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/consumer/consumer.go, control-plane/pkg/security/secrets_provider_legacy_channel_secret.go, control-plane/pkg/security/secrets_provider_net_spec.go, test/e2e-common.sh, test/rekt/features/kafka_source.go, test/rekt/features/kafka_source_create_secrets_after.go
Cherry-pick of https://github.com/knative-extensions/eventing-kafka-broker/commit/05d0cd043cb5fab1da8381954dfdd5c84bae6228
=> [release-v1.15] Support explicit protocol configuration in KafkaChannel secret  (#4126)

openshift/ci-operator/static-images/dispatcher/Dockerfile, openshift/ci-operator/static-images/dispatcher/hermetic/Dockerfile, openshift/ci-operator/static-images/receiver/Dockerfile, openshift/ci-operator/static-images/receiver/hermetic/Dockerfile
Adding the LICENSE file in the static images (similar to #1360).
=> [release-v1.15] Add LICENSE file to Java static-images

.konflux/applications/serverless-operator-136/components/kn-ekb-dispatcher-116.yaml, .konflux/applications/serverless-operator-136/components/kn-ekb-receiver-116.yaml, .konflux/applications/serverless-operator-136/tests/ec-test.yaml, .tekton/docker-java-build.yaml
Add Konflux components and pipelines
=> [release-v1.16] Add Konflux configurations

go.sum, openshift/ci-operator/knative-images/event_display/Dockerfile, openshift/ci-operator/knative-images/heartbeats/Dockerfile, openshift/ci-operator/knative-images/kafka-controller/Dockerfile, openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile, openshift/ci-operator/knative-images/migrate/Dockerfile, openshift/ci-operator/knative-images/post-install/Dockerfile, openshift/ci-operator/knative-images/webhook-kafka/Dockerfile, openshift/ci-operator/knative-test-images/committed-offset/Dockerfile, openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile, openshift/ci-operator/knative-test-images/event-sender/Dockerfile, openshift/ci-operator/knative-test-images/eventshub/Dockerfile, openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile, openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile, openshift/ci-operator/knative-test-images/print/Dockerfile, openshift/ci-operator/knative-test-images/recordevents/Dockerfile, openshift/ci-operator/knative-test-images/request-sender/Dockerfile, openshift/ci-operator/knative-test-images/watch-cm/Dockerfile, openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile, openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile, openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile, openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile, openshift/release/artifacts/eventing-kafka-controller.yaml, openshift/release/artifacts/eventing-kafka.yaml
Run `make generate-release` using openshift-knative/hack.
=> [release-v1.16] Run `make generate-release`

control-plane/pkg/reconciler/base/reconciler.go, control-plane/pkg/reconciler/base/reconciler_test.go, control-plane/pkg/reconciler/broker/broker.go, control-plane/pkg/reconciler/broker/controller.go, control-plane/pkg/reconciler/channel/channel.go, control-plane/pkg/reconciler/channel/controller.go, control-plane/pkg/reconciler/consumer/consumer.go, control-plane/pkg/reconciler/sink/controller.go, control-plane/pkg/reconciler/sink/kafka_sink.go, control-plane/pkg/reconciler/trigger/trigger.go, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java, data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/OIDCDiscoveryConfigListener.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java, data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java, data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java, data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/AbstractDataPlaneTest.java
Backports of the following:
* https://github.com/knative-extensions/eventing-kafka-broker/pull/4055
* https://github.com/openshift-knative/eventing-kafka-broker/pull/1355
=> [release-v1.15] do not build OIDC config unless enabled

go.mod, go.sum, vendor/golang.org/x/net/LICENSE, vendor/golang.org/x/net/http2/client_conn_pool.go, vendor/golang.org/x/net/http2/config.go, vendor/golang.org/x/net/http2/config_go124.go, vendor/golang.org/x/net/http2/config_pre_go124.go, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/http2.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/golang.org/x/net/http2/unencrypted.go, vendor/golang.org/x/net/http2/write.go, vendor/golang.org/x/sys/unix/syscall_dragonfly.go, vendor/golang.org/x/sys/windows/dll_windows.go, vendor/modules.txt
Addresses https://github.com/advisories/GHSA-w32m-9786-jp63
=> [release-v1.15] Update golang.org/x/net to 0.34.0

data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherMutatorChain.java, data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/CloudEventOverridesMutator.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherMutatorChainTest.java, data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/CloudEventOverridesMutatorTest.java
Cherry-pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/4128
=> [release-v1.15] Discard invalid consumer records (#4128)

openshift/e2e-common.sh
=> Run AuthZ tests as part of Encryption/Auth test suite too

.github/workflows/dependabot-deps.yaml, .tekton/docker-build.yaml, .tekton/docker-java-build.yaml
Update Konflux components and pipelines
=> [release-v1.16] Update Konflux configurations

.github/workflows/dependabot-deps.yaml, .tekton/docker-build.yaml, .tekton/docker-java-build.yaml
Update Konflux components and pipelines
=> [release-v1.15] Update Konflux configurations

.github/workflows/dependabot-deps.yaml, .tekton/docker-build.yaml, .tekton/docker-java-build.yaml
Update Konflux components and pipelines
=> [release-v1.17] Update Konflux configurations

data-plane/pom.xml
=> Update Quarkus to 3.8.6.SP3-redhat-00002

control-plane/cmd/post-install/kafka_channel_deployment_deleter.go, control-plane/cmd/post-install/kafka_namespaced_broker_deployment_deleter.go, control-plane/cmd/post-install/main.go
See https://issues.redhat.com/browse/SRVKE-1709
=> [release-v1.15] Fix post install being stuck if the channels are not enabled

data-plane/pom.xml, openshift/ci-operator/static-images/dispatcher/hermetic/Dockerfile.deps, openshift/ci-operator/static-images/receiver/hermetic/Dockerfile.deps
To mitigate missing smallrey jar.
=> Alternative hermetic setup + Quarkus 3.15.z update

README.md
=> Add note how to fetch Quarkus version

go.mod, openshift/ci-operator/build-image/Dockerfile, openshift/ci-operator/knative-images/event_display/Dockerfile, openshift/ci-operator/knative-images/heartbeats/Dockerfile, openshift/ci-operator/knative-images/kafka-controller/Dockerfile, openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile, openshift/ci-operator/knative-images/migrate/Dockerfile, openshift/ci-operator/knative-images/post-install/Dockerfile, openshift/ci-operator/knative-images/webhook-kafka/Dockerfile, openshift/ci-operator/knative-test-images/committed-offset/Dockerfile, openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile, openshift/ci-operator/knative-test-images/event-sender/Dockerfile, openshift/ci-operator/knative-test-images/eventshub/Dockerfile, openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile, openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile, openshift/ci-operator/knative-test-images/print/Dockerfile, openshift/ci-operator/knative-test-images/recordevents/Dockerfile, openshift/ci-operator/knative-test-images/request-sender/Dockerfile, openshift/ci-operator/knative-test-images/watch-cm/Dockerfile, openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile, openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile, openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile, openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile, openshift/generate.sh
Needed on https://github.com/openshift-knative/eventing-kafka-broker/pull/1655#issuecomment-2820940215
=> [release-v1.16] Update to golang 1.23

go.mod, openshift/ci-operator/build-image/Dockerfile, openshift/ci-operator/knative-images/event_display/Dockerfile, openshift/ci-operator/knative-images/heartbeats/Dockerfile, openshift/ci-operator/knative-images/kafka-controller/Dockerfile, openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile, openshift/ci-operator/knative-images/migrate/Dockerfile, openshift/ci-operator/knative-images/post-install/Dockerfile, openshift/ci-operator/knative-images/webhook-kafka/Dockerfile, openshift/ci-operator/knative-test-images/committed-offset/Dockerfile, openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile, openshift/ci-operator/knative-test-images/event-sender/Dockerfile, openshift/ci-operator/knative-test-images/eventshub/Dockerfile, openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile, openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile, openshift/ci-operator/knative-test-images/print/Dockerfile, openshift/ci-operator/knative-test-images/recordevents/Dockerfile, openshift/ci-operator/knative-test-images/request-sender/Dockerfile, openshift/ci-operator/knative-test-images/watch-cm/Dockerfile, openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile, openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile, openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile, openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile, openshift/generate.sh
=> [release-v1.17] Update golang 1.23

control-plane/config/post-install/200-controller-cluster-role.yaml, openshift/release/artifacts/eventing-kafka-post-install.yaml, openshift/release/artifacts/eventing-kafka.yaml
https://issues.redhat.com/browse/SRVKE-1583
=> [release-v1.16] Patch knative kafka controller post install role rule attribute

control-plane/config/post-install/200-controller-cluster-role.yaml, openshift/release/artifacts/eventing-kafka-post-install.yaml, openshift/release/artifacts/eventing-kafka.yaml
manual backport of https://github.com/openshift-knative/eventing-kafka-broker/pull/1809/files to here
=> [release-v1.17] Patch knative kafka controller post install role rule attribute

test/e2e_new/broker_test.go, test/e2e_new/kafka_source_test.go, test/rekt/features/keda_scaling.go
=> [release-v1.16] Enable new test for SASL keda

openshift/e2e-common.sh
Currently we install cert-manager after we installed Strimzi/Kafka. This leads to the following issue (see https://github.com/openshift-knative/eventing-kafka-broker/pull/1813#issuecomment-2933153587):
```
Create Kafka Certificate
error: resource mapping not found for name: "my-cluster-kafka" namespace: "" from "./test/kafka/kafka-certificate.yaml": no matches for kind "Certificate" in version "cert-manager.io/v1"
ensure CRDs are installed first
```
This PR addresses it and installs cert-manager before installing Kafka
=> Install cert-manager before installing Kafka

.tekton/docker-build.yaml, .tekton/docker-java-build.yaml
Update Konflux components and pipelines
=> [release-v1.18] Update Konflux configurations
