- openshift/e2e-common.sh
- openshift/e2e-tests.sh
this adds scripts to install "Serverless" and Kafka
More to come:
* Part II: enable on Prow
* Part III replace images
* Part IV see the e2e run
> Adding install base for running CI... part I

- vendor/knative.dev/pkg/version/version.go
Doing https://github.com/openshift/knative-eventing/pull/1470  for here too...
/hold
not sure if we should merge that ... now ...
> Patch min. version for OCP 4.6

- test/e2e/broker_trigger_sink_test.go
- test/e2e/kafka_sink_test.go
- test/e2e/sacura_test.go
- vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml
- vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
- vendor/knative.dev/reconciler-test/pkg/images/ko.go
Backports from 0.26
the `nightly` images will be replaced, once we have `eventing 1.0` branch on CI ...
> More test tweaks

- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/KafkaConsumerRecordUtils.java
- data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/DataPlaneTest.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1502
> [release-v0.26] Properly handle events without the `data` field

- openshift/ci-operator/knative-images/broker-dispatcher/Dockerfile
- openshift/ci-operator/knative-images/broker-receiver/Dockerfile
As per title, and closing https://github.com/openshift-knative/eventing-kafka-broker/pull/42
Just using the `ubi minimal`
> Using UBI 8 with Java-17 image as Runtime

- openshift/e2e-common.sh
- openshift/release/generate-release.sh
- openshift/release/knative-eventing-kafka-broker-dp-ci.yaml
- openshift/release/resolve.sh
Updating the generator to ensure we use the proper `sink-receiver` and use explict `-broker` or `-sink` prefixes
> [release-v1.0] Using sink receiver

- test/config/monitoring.yaml
manual backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/1270
> [release-v0.26] Download zipkin from Github's container registry

- test/kafka/kafka_setup.sh
This is breaking the build in https://github.com/openshift-knative/eventing-kafka-broker/pull/59
> [release-0.26] Add client value to --dry-run command line argument

- test/pkg/broker/broker.go
- test/pkg/testing/run.go
> [release-v1.0] Use Broker's own configmap for Kafka

- openshift/ci-operator/knative-images/sink-receiver/Dockerfile
like: https://github.com/openshift-knative/eventing-kafka-broker/pull/46
just for the sink receiver image
> Using UBI 8 OpenJDK-17 image as Runtime

- openshift/ci-operator/generate-ci-config.sh
- openshift/ci-operator/update-ci.sh
Porting relevant bits from:
* openshift/knative-eventing/pull/1487
*  openshift/knative-eventing/pull/1495
to the broker midstream main stash.
**NOTE:** Intentionally, I left the image mirror out, as we do not really need that - yet ... 
> Port changes from eventing fork to broker fork

- vendor/knative.dev/pkg/injection/sharedmain/main.go
Similar to #65  with out this patch, and a `disable-controllers` ARG, I get:
```shell
Args:
--disable-controllers=source-controller
State:       Waiting
Reason:    CrashLoopBackOff
Last State:  Terminated
Reason:    Error
Message:   flag provided but not defined: -disable-controllers
```
Patching here, since https://github.com/knative/pkg/pull/2379/commits/798325101e01844dd418295d57714c063393be0a was not merged.... will revisit.
But without this -> not working
> :dizzy: using flags, since we already use that via ParseAndGetRESTConfigOrDie

- openshift/ci-operator/generate-ci-config.sh
- openshift/e2e-common.sh
- openshift/release/generate-release.sh
- openshift/release/resolve.sh
As per title.
Here is a list of commits, where I used the different patches for our _scripts_ (not on generated files):
* https://github.com/openshift-knative/eventing-kafka-broker/commit/1caea011e697b118b514553d2ed5fe30da438805#diff-d1f6a0b482e1186e9e185284cbc46751b4d0ddd6c510abeadc21ce798ee192d6
* https://github.com/openshift-knative/eventing-kafka-broker/commit/9e02488963ff1c6b6f01f5dda8fa9895a2c82ab8#diff-d1f6a0b482e1186e9e185284cbc46751b4d0ddd6c510abeadc21ce798ee192d6
* https://github.com/openshift-knative/eventing-kafka-broker/commit/eed13f2ec2243c920aaab378c53c2c0d6918668a#diff-d1f6a0b482e1186e9e185284cbc46751b4d0ddd6c510abeadc21ce798ee192d6
* https://github.com/openshift-knative/eventing-kafka-broker/commit/85b5a1cb476bf6ccfe …
> Reuse of different patches stashing them on `main` branch

- openshift/release/generate-release.sh
as per title, and script part of https://github.com/openshift-knative/eventing-kafka-broker/pull/85  ported to `main`
> [`main`] Adding channel to the DP generator

- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
Bringing https://github.com/knative-sandbox/eventing-kafka-broker/pull/1750 to our 1.1 midstream
> [release-v1.1] Bounded unordered delivery outbound events for backpressure (#1838)

- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
Bringing https://github.com/knative-sandbox/eventing-kafka-broker/pull/1750 to our 1.0 midstream
> [release-v1.0] Bounded unordered delivery outbound events for backpressure (#1838)

- openshift/release/create-release-branch.sh
* older branches did not have any workflows
> Use --allow-empty for removing github workflows

- Makefile
* There are static images brought by
https://github.com/openshift-knative/eventing-kafka-broker/commit/f006911ce1048c7f1ef18dc42b51c5228d3dd0a4
* They should not be deleted when generating new Dockerfiles from
update-to-head.sh script
The bug prevents from running CI against release-next branch as pursued here: https://github.com/openshift/release/pull/26046
Example error: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/26046/rehearse-26046-pull-ci-openshift-knative-eventing-kafka-broker-release-next-49-conformance-aws-ocp-49/1490705034487271424
> Do not remove existing Dockerfiles before generating new ones

- openshift/release/resolve.sh
* YAML allows the following syntax when xyz is actually still taken as
as a comment. But removing the line with the # sign will cause a failure
when applying this yaml file because xyz is suddenly not a comment.
```
data:
_example: |
#
xyz
```
We use this pattern e.g. here:
https://github.com/knative-sandbox/eventing-kafka-broker/blob/e32c88296d90f95a99d15a0dc649a9238e1ee819/control-plane/config/200-controller/100-config-kafka-descheduler.yaml#L43
> Do not remove comments when resolving yaml files for CI

- control-plane/pkg/prober/async_prober.go
- control-plane/pkg/prober/async_prober_test.go
- control-plane/pkg/prober/prober.go
- control-plane/pkg/prober/prober_test.go
- control-plane/pkg/prober/probertesting/mock_prober.go
- control-plane/pkg/prober/probertesting/mock_prober_test.go
- control-plane/pkg/reconciler/broker/broker.go
- control-plane/pkg/reconciler/channel/channel.go
- control-plane/pkg/reconciler/sink/kafka_sink.go
Cherry-pick of: 
https://github.com/knative-sandbox/eventing-kafka-broker/pull/1914/files
When we probe for resource status, we want to avoid probing the
pod when the status is in our expected status.
Before this patch, we had an hard-coded expected status of
`StatusReady`, which is wrong in the `FinalizeKind` case.
> [release-v1.0] Add expected status to prober

- control-plane/cmd/webhook-kafka/main.go
We don't need this webhook for v1.21.
> [release-v1.1] Remove KafkaChannel webhook

- control-plane/pkg/reconciler/broker/broker.go
Upstream/1987 PR moved to here
> We removed the "add finalizer to the ConfigMap logic" in
https://github.com/knative-sandbox/eventing-kafka-broker/pull/1971
and we kept the "remove the ConfigMap finalizer" in `FinalizeKind`.
> However, in order to remove the ConfigMap finalizer from every
existing Broker that won't be deleted in the time span going from
1.3 to whatever release we remove the logic to remove the finalizer.
> Signed-off-by: Pierangelo Di Pilato <pierdipi@redhat.com>
> [release-v1.1] Backport of upstream 1987

- control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-leader-election.yaml
- hack/control-plane.sh
- openshift/patches/support-map-lease-prefix-in-pkg.patch
- openshift/release/knative-eventing-kafka-broker-cp-ci.yaml
- test/e2e-common.sh
- test/e2e_new/features/leases.go
- test/e2e_new/lease_test.go
- vendor/knative.dev/pkg/configmap/parse.go
- vendor/knative.dev/pkg/leaderelection/config.go
- vendor/knative.dev/pkg/leaderelection/context.go
To actually cherry-pick https://github.com/knative-sandbox/eventing-kafka-broker/commit/3599d8f13b037c450cfa6a07bbb23664c99ca348, we need
some additional patches for knative/pkg.
See individual commits for details.
> [release-v1.1] KafkaSource lease remapping

- control-plane/cmd/post-install/main.go
- control-plane/cmd/post-install/so_kafka_source_deleter.go
- control-plane/config/post-install/200-controller-cluster-role.yaml
SO creates dynamically the service and the associated service
monitor to scrape metrics.
This additional logic will make sure these are removed.
> [release-v1.1] Delete service monitors for KafkaSource

- control-plane/cmd/post-install/main.go
Got this error since injection isn't enabled:
```
panic: Unable to fetch k8s.io/client-go/dynamic.Interface from context.
goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00028aa80, {0x0, 0x0, 0x0})
/go/src/knative.dev/eventing-kafka-broker/vendor/go.uber.org/zap/zapcore/entry.go:232 +0x446
go.uber.org/zap.(*SugaredLogger).log(0xc000012010, 0x4, {0x0, 0x0}, {0xc00062fde8, 0xc00062fdf8, 0x11eee5d}, {0x0, 0x0, 0x0})
/go/src/knative.dev/eventing-kafka-broker/vendor/go.uber.org/zap/sugar.go:227 +0xee
go.uber.org/zap.(*SugaredLogger).Panic(...)
/go/src/knative.dev/eventing-kafka-broker/vendor/go.uber.org/zap/sugar.go:123
knative.dev/pkg/injection/clients/dynamicclient.Get({0x190cfa8, 0xc000012020})
/go/src/knative.dev/eventing-kafka-broker/vendor/knative.dev/pkg/injection …
```
> [release-v1.1] Use dynamic client constructor

- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
Dynamically set `max.poll.interval.ms` based on the delivery spec (#2060)
`max.poll.interval.ms` is used to bound the processing time at
the consumer level, however, we have application-level timeouts
that are dinamically controlled.
In this patch, I'm performing the maximum processing time (
see how in `maxProcessingTimeMs` method) and set
`max.poll.interval.ms` to that value.
Co-authored-by: Pierangelo Di Pilato <pierdipi@redhat.com>
> [release-v1.3] backport of #2060

- control-plane/cmd/post-install/so_kafka_source_deleter.go
We were using the Kind name instead of the resource name.
> Fix resource name servicemonitors

- openshift/release/knative-eventing-kafka-broker-cp-ci.yaml
- openshift/release/knative-eventing-kafka-broker-dp-ci.yaml
- openshift/release/resolve.sh
By removing lines starting with `#`, we produce invalid YAMLs.
I think it's reasonable to keep them because in this midstream
repository we just need something that we can apply.
I don't know the reason of removing comments, so if you have more
insights, I'd be happy to discuss them.
> [release-v1.3] Remove deletions of comments when resolving YAMLs

- data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java
- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/CloudEventDeserializer.java
- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/InvalidCloudEvent.java
- data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherTest.java
- data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/CloudEventDeserializerTest.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/5ca60b009fc14da76a7a35554bfa56a9be765959
* Skip Consumer records that are not CloudEvents
Signed-off-by: aavarghese <avarghese@us.ibm.com>
* Update description for new metric
Co-authored-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
* Update string value for new metric
Co-authored-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
* Review updates
Signed-off-by: aavarghese <avarghese@us.ibm.com>
Co-authored-by: aavarghese <avarghese@us.ibm.com>
Co-authored-by: Pierangelo Di Pilato <pierangelodipilato@gmail.com>
> [release-v1.1] Skip Consumer records that are not CloudEvents (#2072)

- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
As discussed previously, the default timeout of 10 seconds isn't
sometimes enough to even start a Knative Service.
Using 10 minutes will avoid overriding the timeout with
`spec.delivery.timeout` in most of the use cases.
> [release-v1.1] Increase default timeout to 10 minutes (#2057)

- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/UnorderedConsumerVerticle.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/dcb1a6e5044981daa485c2c07c85b2f1c269ec6c
* Limit the number of poll calls for unordered delivery
Multiple async `poll` calls can lead to a large number of records
loaded into memory and dispatched to subscribers.
In this PR, I'm limiting the number of poll requests to 1.
> [release-v1.1] Limit the number of poll calls for unordered delivery (#2095)

- openshift/release/generate-release.sh
Tried these changes locally and now all conformance tests pass on release-next branch. The E2E tests still have some failures: `DONE 826 tests, 2 skipped, 23 failures in 1766.126s` A lot of the failures are related to already existing resources, similar to:
```
kafka_helper.go:243: Error while creating the topic initial-topicchange-bootstrap-server: kafkatopics.kafka.strimzi.io "initial-topicchange-bootstrap-server" already exists
```
> Process 100-channel and 100-kafka-internal

- openshift/patches/SO-uses-different-post-install-job-names.patch
- test/upgrade/postupgrade.go
This is blocking https://github.com/openshift-knative/serverless-operator/pull/1516
> [release-v1.2] Skip tests that expects specific post-install job names

- Makefile
- openshift/e2e-common.sh
* enabling the `run_e2e_new_tests` function
* updating "rekt test" image versions (a bit of manual work, currently)
> [release-v1.2] Execute new e2e test suite on OCP

- control-plane/pkg/reconciler/channel/channel.go
No reason to do an error log, since we do have a default value to be used. Going with debug to reduce verbosity...
> [release-v1.2] Going with debug to reduce verbosity for retention duration default usage

- openshift/patches/override-rekt-images.patch
- openshift/release/artifacts/eventing-kafka-broker.yaml
- openshift/release/artifacts/eventing-kafka-channel.yaml
- openshift/release/artifacts/eventing-kafka-sink.yaml
- openshift/release/artifacts/eventing-kafka-source.yaml
- vendor/knative.dev/eventing-kafka/test/e2e/helpers/channel_subscription_ready_test_helper.go
- vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml
- vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml
- vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
- vendor/knative.dev/eventing/test/test_images/event-sender/pod.yaml
- vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml
- vendor/knative.dev/eventing/test/test_images/performance/pod.yaml
- vendor/knative.dev/eventing/test/test_images/print/pod.yaml
- vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml
- vendor/knative.dev/eventing/test/test_images/request-sender/pod.yaml
- vendor/knative.dev/eventing/test/test_images/wathola-fetcher/pod.yaml
- vendor/knative.dev/eventing/test/test_images/wathola-forwarder/pod.yaml
- vendor/knative.dev/eventing/test/test_images/wathola-receiver/pod.yaml
- vendor/knative.dev/eventing/test/test_images/wathola-sender/pod.yaml
* Adding a correct version rekt test image replacement patch
* MAKE RELEASE  (does revert FIPS, on purpose).
Next: do a better FIPS patch
> Update patches for rekt images 1.2

- control-plane/cmd/post-install/kafka_channel_migrator.go
I get this error after upgrading
```
"ReconcileKind","error":"failed to get secret: failed to get secret knative-eventing/: resource name may not be empty"
```
The CM created by the post-install job is like this:
```
{
"apiVersion": "v1",
"data": {
"auth.secret.ref.name": "",
"auth.secret.ref.namespace": "",
"bootstrap.servers": "my-cluster-kafka-bootstrap.kafka:9092"
},
"kind": "ConfigMap",
"metadata": {
"creationTimestamp": "2022-05-10T18:33:49Z",
"labels": {
"kafka.eventing.knative.dev/release": "v1.2.3"
},
"name": "kafka-channel-config",
"namespace": "knative-eventing",
"ownerReferences": [
{
"apiVersion": "operator.serverless.openshift.io/v1alpha1",
"blockOwnerDeletion": true,
"controller": true,
"kind": "KnativeKafka",
"name": "knative-kafka",
"uid": …
```
> [v1.2] KafkaChannel migrator adds the secret ref only when previously specificied

- data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
> Backport from upstream
Vert.x's client, server and verticles metrics adds a lot of
allocations and their metrics exposed add little value in a
kubernetes environment or our case.
Co-authored-by: Pierangelo Di Pilato <pierdipi@redhat.com>
> [release-v1.2 ]Disable unnecessary metrics (#2156)

- control-plane/cmd/post-install/kafka_channel_post_migration_deleter.go
> [release-v1.2] Remove old Config Kafka CM for old/legacy channel

- openshift/patches/use_kafkacat_from_ocp.patch
- vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_helper.go
patch to use our stashed version of `kafkacat`
> [release-v1.2] Use openshift knative kafkacat

- control-plane/pkg/reconciler/kafka/client.go
- go.mod
- vendor/modules.txt
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2225
Sarama metrics consume a lot of memory but we don't use/expose them.
> [release-v1.2] Disable Sarama metrics since they are not exposed (#2225)

- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/BaseConsumerVerticle.java
- data-plane/dispatcher/src/test/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/AbstractConsumerVerticleTest.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2277
In an E2E test run, we saw that failing to close a consumer
will cause the reconcile to stop reconciling resources.
- [1] the data plane reconciler saw that we need to remove a
resource
- since the previous removal never "completes" (as we're
waiting for the callback to complete), newer contract
generations [2] are never reconciled
[1]
```
{"@timestamp":"2022-06-06T11:46:44.775Z","@version":"1","message":"Set new contract contractGeneration=107","logger_name":"dev.knative.eventing.kafka.broker.core.reconciler.impl.ResourcesReconcilerMessageHandler","thread_name":"vert.x-eventloop-thread-0","level":"INFO","level_value":20000,"contractGeneration":107} …
```
> [release-v1.2] Avoid waiting for `Consumer.close` when removing resources (#2277)

- control-plane/pkg/reconciler/channel/channel.go
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/90ef72592e27b8ee893c7252b08cbfe9503e828c
When a subscriber is added or removed, the reconciler won't detect
this change and it won't update the contract generation, leading
to the data plane to skip the reconciliation since a contract
with the same generation is considered the same contract.
> [release-v1.2] Detect subscribers changes in KafkaChannel reconciler (#2304)

- data-plane/config/broker/100-config-kafka-broker-data-plane.yaml
- data-plane/config/channel/100-config-kafka-channel-data-plane.yaml
- data-plane/config/sink/100-config-kafka-sink-data-plane.yaml
- data-plane/config/source/100-config-kafka-source-data-plane.yaml
- openshift/release/artifacts/eventing-kafka-broker.yaml
- openshift/release/artifacts/eventing-kafka-channel.yaml
- openshift/release/artifacts/eventing-kafka-sink.yaml
- openshift/release/artifacts/eventing-kafka-source.yaml
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/ebb10bef89dbe51461bedd9d73fa86006cf06a5c
Big timeouts as before end up parking threads unnecessarily, this is
especially evident when deleting a resource end up having consumers
polling topic/partitions that don't exist anymore until timeouts
are reached.
> [release-v1.2] Reduce consumer and producer timeouts (#2305)

- openshift/ci-operator/Dockerfile.in
- openshift/ci-operator/knative-images/kafka-controller/Dockerfile
- openshift/ci-operator/knative-images/post-install/Dockerfile
- openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
- openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
- openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
- openshift/ci-operator/knative-test-images/event-flaker/Dockerfile
- openshift/ci-operator/knative-test-images/event-library/Dockerfile
- openshift/ci-operator/knative-test-images/event-sender/Dockerfile
- openshift/ci-operator/knative-test-images/eventshub/Dockerfile
- openshift/ci-operator/knative-test-images/heartbeats/Dockerfile
- openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
- openshift/ci-operator/knative-test-images/partitions-replication-verifier/Dockerfile
- openshift/ci-operator/knative-test-images/performance/Dockerfile
- openshift/ci-operator/knative-test-images/print/Dockerfile
- openshift/ci-operator/knative-test-images/recordevents/Dockerfile
- openshift/ci-operator/knative-test-images/request-sender/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
In this patch, I'm removing the requirement to build binaries
on the host and then build the image by copying the binary.
This improves consistency because the build isn't different
based on the environment is built.
In addition, this simplifies my openshift/release reconciler.
See only the changes in `openshift/ci-operator/Dockerfile.in`
the rest is generated by `make generate-dockerfiles`
> Self contained dockerfiles for images

- openshift/release/create-release-branch.sh
`release` is the upstream release
> Use target to generate release

- openshift/release/update-to-head.sh
See https://github.com/openshift-knative/eventing-kafka-broker/blob/bfbcd5a2d87e6614ea2903142daa7c34572c271f/openshift/release/generate-release.sh#L7-L8
> Patches are already applied when running make generate-release

- openshift/release/update-to-head.sh
As it was, it is missing some vendor changes created by
`make generate-release`
> [main] Include vendor and other changes in update-to-head.sh

- openshift/patches/SO-uses-different-post-install-job-names.patch
- test/upgrade/postupgrade.go
* Needed by https://github.com/openshift-knative/serverless-operator/pull/1652
* As in #219
> Skip tests that expects specific post-install job names (#220)

- openshift/patches/close_offsetmanager.patch
- vendor/knative.dev/eventing-kafka/pkg/common/kafka/offset/offsets.go
The OffsetManager wasn't closed after initializing the offsets
leading to go routing leaks.
Backport https://github.com/knative-sandbox/eventing-kafka/pull/1214/commits/a56979ca6e0f7981cf5a609027905c76729cdfed
using a vendor patch.
> [SRVKE-1249][release-v1.3] Close OffsetManager on init offsets

- openshift/patches/SO-uses-different-post-install-job-names.patch
Add this patch [1] to main branch.
[1] https://github.com/openshift-knative/eventing-kafka-broker/commit/249d203ec40edeef6520203f9f553afbf75f9b8a
> [main] Skip tests that expects specific post-install job names

- openshift/patches/remove_checksum_generation_for_config_tracing.patch
- openshift/release/generate-release.sh
Cherry-pick of https://github.com/openshift-knative/eventing-kafka-broker/pull/353
`config-tracing` is removed during the make generate-release command
since it will come from eventing core, so `./hack/update-checksum.sh`
fails since it can find the YAML.
> [main] Do not generate checksum for config tracing

- hack/update-checksums.sh
- openshift/patches/remove_checksum_generation_for_config_tracing.patch
- openshift/release/artifacts/eventing-kafka-broker.yaml
- openshift/release/artifacts/eventing-kafka-channel.yaml
- openshift/release/artifacts/eventing-kafka-controller.yaml
- openshift/release/artifacts/eventing-kafka-post-install.yaml
- openshift/release/artifacts/eventing-kafka-sink.yaml
- openshift/release/artifacts/eventing-kafka-source.yaml
- openshift/release/artifacts/eventing-kafka.yaml
- openshift/release/generate-release.sh
- vendor/knative.dev/eventing/test/rekt/resources/containersource/containersource.yaml
- vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml
- vendor/knative.dev/eventing/test/rekt/resources/flaker/flaker.yaml
- vendor/knative.dev/eventing/test/test_images/event-sender/pod.yaml
- vendor/knative.dev/eventing/test/test_images/heartbeats/pod.yaml
- vendor/knative.dev/eventing/test/test_images/performance/pod.yaml
- vendor/knative.dev/eventing/test/test_images/print/pod.yaml
- vendor/knative.dev/eventing/test/test_images/recordevents/pod.yaml
- vendor/knative.dev/eventing/test/test_images/request-sender/pod.yaml
- vendor/knative.dev/eventing/test/test_images/wathola-fetcher/pod.yaml
- vendor/knative.dev/eventing/test/test_images/wathola-forwarder/pod.yaml
- vendor/knative.dev/eventing/test/test_images/wathola-receiver/pod.yaml
- vendor/knative.dev/eventing/test/test_images/wathola-sender/pod.yaml
- vendor/knative.dev/reconciler-test/pkg/eventshub/103-pod.yaml
`config-tracing` is removed during the make generate-release command
since it will come from eventing core, so `./hack/update-checksum.sh`
fails since it can find the YAML.
> [release-v1.4] Do not generate checksum for config tracing

- openshift/e2e-common.sh
This command:
```
export ON_CLUSTER_BUILDS=true
export DOCKER_REPO_OVERRIDE=image-registry.openshift-image-registry.svc:5000/openshift-marketplace
make images
```
ensures that the artifacts used by the operator are based on the
artifacts in the branch we're testing instead of the one in SO.
> [release-v1.4] Rebuild operator manifests to ensure YAMLs are injected

- data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/metrics/Metrics.java
- data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnv.java
- data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/utils/BaseEnvTest.java
- data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverEnvTest.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/79e2c2ac703640f1e600f78a2f5d8e9539aa66d7
> [release-v1.4] Allow enabling data plane server and client metrics (#2436)

- data-plane/config/broker/100-config-kafka-broker-data-plane.yaml
- data-plane/config/channel/100-config-kafka-channel-data-plane.yaml
- data-plane/config/source/100-config-kafka-source-data-plane.yaml
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/22e73fd97d19fb646b6c0e195bebab09ba6e9491
> [release-v1.4] Reduce default max.poll.records and max.partition.fetch.bytes (#2456)

- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleFactoryImpl.java
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/commit/fe37776828e85c46524c7d82b5e8e54a789e9443
> [release-v1.4] Perform `max.poll.interval.ms` considering `max.poll.records` (#2439)

- test/pkg/addressable/send.go
Backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2421
Running them in separate t.Run functions causes issues such as the
following one because events might be sent after the t.Run ends since
they run in separate go routines in background:
panic: Fail in goroutine after
TestKafkaSinkV1Alpha1AuthPlaintext/1/send_event_0 has completed
goroutine 6809 [running]:
testing.(*common).Fail(0xc002b5c340)
/root/.gvm/gos/go1.17.8/src/testing/testing.go:710 +0x1b4
testing.(*common).FailNow(0xc002b5c340)
/root/.gvm/gos/go1.17.8/src/testing/testing.go:732 +0x2f
testing.(*common).Fatalf(0xc00437a000, {0x2b71c16, 0x22}, {0xc004acfbd8,
0x3, 0x3})
/root/.gvm/gos/go1.17.8/src/testing/testing.go:830 +0x85
knative.dev/eventing/test/lib.(*Client).SendEvent(0xc0035c2d20,
{0x3137bb0, …
> [release-v1.4] SendN sends events in a common t.Run

- test/pkg/addressable/send.go
Backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2421
Running them in separate t.Run functions causes issues such as the
following one because events might be sent after the t.Run ends since
they run in separate go routines in background:
panic: Fail in goroutine after
TestKafkaSinkV1Alpha1AuthPlaintext/1/send_event_0 has completed
goroutine 6809 [running]:
testing.(*common).Fail(0xc002b5c340)
/root/.gvm/gos/go1.17.8/src/testing/testing.go:710 +0x1b4
testing.(*common).FailNow(0xc002b5c340)
/root/.gvm/gos/go1.17.8/src/testing/testing.go:732 +0x2f
testing.(*common).Fatalf(0xc00437a000, {0x2b71c16, 0x22}, {0xc004acfbd8,
0x3, 0x3})
/root/.gvm/gos/go1.17.8/src/testing/testing.go:830 +0x85
knative.dev/eventing/test/lib.(*Client).SendEvent(0xc0035c2d20,
{0x3137bb0, …
> [release-v1.3] SendN sends events in a common t.Run

- test/pkg/kafka/verify_num_partitions_replication.go
Set TerminationMessagePolicy=FallbackToLogsOnError for partition-replication-factor-verifier so that we can see the failure in the pod status
Backport https://github.com/knative-sandbox/eventing-kafka-broker/pull/2627
> [1.4] Set TerminationMessagePolicy=FallbackToLogsOnError for partition-replication-factor-verifier so that we can see the failure in the pod status

- data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/reconciler/impl/ResourcesReconcilerImpl.java
When egress changes are detected log the egress info
at debug level instead of logging egresses that weren't
changed at info.
Cherry-pick of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2652
> Remove noisy log lines "Nothing changed" at info level

- data-plane/config/broker/500-dispatcher.yaml
- data-plane/config/broker/500-receiver.yaml
- data-plane/config/brokerv2/500-dispatcher.yaml
- data-plane/config/channel/500-dispatcher.yaml
- data-plane/config/channel/500-receiver.yaml
- data-plane/config/channelv2/500-dispatcher.yaml
- data-plane/config/sink/500-receiver.yaml
- data-plane/config/sourcev2/500-dispatcher.yaml
- openshift/release/artifacts/eventing-kafka-broker.yaml
- openshift/release/artifacts/eventing-kafka-channel.yaml
- openshift/release/artifacts/eventing-kafka-sink.yaml
- openshift/release/artifacts/eventing-kafka.yaml
For the 1.4 we may potentially also disable the FIPS check.
On purpose I am not adding a "patch" to the `openshift/patches` folder since hopefully we will soon have a base image, and we do not need this tweak.
However, for now, we should include, unfortunately like on older releases.
> [release-v1.4] Include fips disabled flag

- openshift/ci-operator/build-image/Dockerfile
Fix the following error:
```
STEP 5/8: RUN GO111MODULE=on go get github.com/mikefarah/yq/v3
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
> [main] Use go install instead of deprecated go get

- .github/workflows/multiarch-build.yaml
- .ko.yaml
- Makefile
Same as https://github.com/openshift-knative/eventing-kafka-broker/pull/419, just merging all commits into one to have a good example for future similar changes in other repositories (Serving, Eventing, etc.).
* Align base image for ko with CI
* Github workflow for building multiarch test images
> [release-v1.5] Github action for building multiarch test images

- openshift/e2e-common.sh
I think there is no need to run this test in SO.
It takes to much time to complete and we're already running it in this repository.
> [release-v1.5] Add flag to avoid running first-event-delay test in SO since it is too slow

- openshift/e2e-common.sh
Cherry-pick of https://github.com/openshift-knative/eventing-kafka-broker/commit/35bf58b38ae705e82252b5cd57894e34f44551b7
> [main] Add flag to avoid running first-event-delay test in SO since it is too slow

- openshift/e2e-common.sh
A little cleanup, it was previously needed because we didn't have the
dynamic update for config-tracing configurations.
> [main] cleanup: Install Kafka directly

- openshift/patches/remove_seccomp_profile.patch
This config is not available in any supported OCP, it will be added dynamically in [1].
[1] https://github.com/openshift-knative/serverless-operator/pull/1773
> [main] Remove seccompProfile config patch

- openshift/patches/security-context-for-test-pods.patch
- vendor/knative.dev/eventing/test/lib/creation.go
Add remaining vendor changes from https://github.com/openshift/knative-eventing/commit/6ea60fb516fc80f5db539e8ef68c1b95abe50036
> [release-v1.5] Use AllowRestrictedPodSecurityStandard in vendored creation.go

- openshift/patches/override-min-version.patch
Error:
```
01:35:21  error: patch failed: vendor/knative.dev/pkg/version/version.go:33
01:35:21  error: vendor/knative.dev/pkg/version/version.go: patch does not apply
```
> [main] Update k8s min version patch since it failed in the periodic update

- test/kafka/user-sasl-scram-512.yaml
- test/kafka/user-tls.yaml
backport the ACL part of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2381 to release-v1.5
authorize kafka test users to delete topics, so that the testsuites can cleanup by themselves,
> [release-v1.5] backport topic Delete ACL to kafka users

- control-plane/pkg/reconciler/consumergroup/consumergroup.go
- data-plane/config/source/500-dispatcher.yaml
- go.mod
- openshift/release/artifacts/eventing-kafka-source.yaml
- openshift/release/artifacts/eventing-kafka.yaml
The pod lister lists old pods in addition to the statefulset
related ones because they have the same
`app: kafka-source-dispatcher` label.
> [release-v1.6] Source v2 pod version selector for upgrade

- openshift/patches/skip_namespaced_broker_propagation_test.patch
Here's the reason for this: https://github.com/openshift-knative/eventing-kafka-broker/pull/499
> [main] Add patch to skip namespaced broker propagation test

- control-plane/config/eventing-kafka-broker/200-controller/200-controller-cluster-role.yaml
- control-plane/config/post-install/200-controller-cluster-role.yaml
- data-plane/config/broker/200-broker-data-plane-cluster-role.yaml
- data-plane/config/channel/200-channel-data-plane-cluster-role.yaml
- data-plane/config/sink/200-sink-data-plane-cluster-role.yaml
- data-plane/config/source/200-source-data-plane-cluster-role.yaml
Backport of https://github.com/knative-sandbox/eventing-kafka-broker/commit/24f402aa786beb4514527d4ef93289f8c1eac790 from upstream, to our 1.7 midstream, as the fix is targeting SO 1.28 (see https://issues.redhat.com/browse/SRVKS-896)
> [release-v1.7] Restrict wildcard rbac apiGroups (#2844)

- control-plane/pkg/reconciler/broker/broker.go
- control-plane/pkg/reconciler/broker/broker_test.go
Partially porting fix for #2829 to OCP.
The "rek test" is missing, due to dependencies mismatch (will be present in 1.9). Reference PR for the base work:
https://github.com/knative/eventing/pull/6645
> [release-v1.7] Do not block finalization if secret for external topic is gone

- openshift/e2e-common.sh
the 1.6 bits should be tested against our 1.27 product branch
> [release-v1.6] Using matching branch

- openshift/patches/use_kafkacat_from_ocp.patch
Fix current CI issue (https://redhat-internal.slack.com/archives/C033PCUSA4X/p1673829335948609):
```
01:35:35  error: vendor/knative.dev/eventing-kafka/test/e2e/helpers/kafka_helper.go: No such file or directory
```
comes from https://github.com/knative-sandbox/eventing-kafka-broker/pull/2878 as the `kafka_helpers.go` file moved to another directory.
> Update patch for kafkaCatImage

- openshift/patches/use_kafkacat_from_ocp.patch
Fix the kafkaCatImage patch to use tabs instead of spaces (copied the patch initially from console output :facepalm: )
> Fix patch for kafkaCatImage

- openshift/release/generate-release.sh
Since the kafkacat patch is not specific to a files in vendor/ anymore, the changes will not be overwritten anymore and thus only needs to run once in the update-to-head.sh.
> Remove kafkacat patch from generate-release.sh

- control-plane/pkg/reconciler/broker/broker.go
- control-plane/pkg/reconciler/broker/broker_test.go
- test/e2e_new/broker_test.go
- test/e2e_new/features/broker_deleted_recreated.go
- test/e2e_new/resources/configmap/broker/broker_config.go
- test/e2e_new/resources/configmap/broker/broker_config.yaml
Backporting upstream #2910
and adding rekt-test missing parts (`with auth secret`)
> [release-v1.7] Backport 2910

- control-plane/pkg/reconciler/broker/broker.go
- control-plane/pkg/reconciler/broker/broker_test.go
- control-plane/pkg/reconciler/testing/objects_broker.go
- test/e2e_new/bogus_config/bogus_config.yaml
- test/e2e_new/bogus_config/install.go
- test/e2e_new/broker_test.go
- test/e2e_new/features/broker_deleted_recreated.go
backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2853
> [releaes-v1.7] Fix invalid config

- control-plane/pkg/reconciler/consumergroup/evictor.go
- control-plane/pkg/reconciler/consumergroup/evictor_test.go
Backport of upstream #2923 
```
E0125 19:04:18.704663       1 runtime.go:79] Observed a panic: "makeslice: cap out of range" (runtime error: makeslice: cap out of range)
goroutine 427 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1d6fba0?, 0x2408810})
/remote-source/knative-kafka-broker/app/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x7fcd35b823a0?})
/remote-source/knative-kafka-broker/app/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x1d6fba0, 0x2408810})
/usr/lib/golang/src/runtime/panic.go:838 +0x207
knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup.removePlacement(...)
```
> [release-v1.7] Fix evictor panic

- control-plane/cmd/kafka-controller/main.go
- control-plane/cmd/kafka-source-controller/main.go
- control-plane/pkg/reconciler/consumergroup/consumergroup.go
- control-plane/pkg/reconciler/source/controller.go
- control-plane/pkg/reconciler/source/controller_test.go
- control-plane/pkg/reconciler/source/source.go
- control-plane/pkg/reconciler/source/source_test.go
- control-plane/pkg/reconciler/source/testdata/config-kafka-features.yaml
- control-plane/pkg/reconciler/testing/factory.go
- control-plane/pkg/reconciler/testing/objects_common.go
Backport of https://github.com/knative-sandbox/eventing-kafka-broker/pull/2919
**Hints for reviewers**
* Had some merge conflicts due to some movement from eventing-kafka to EKB repo
* `pkg/autoscaler/keda` did not exist in 1.7, so used `pkg/keda`
/cc @pierDipi
> [release-v1.7] Improve source reconciler KEDA enabled check

- openshift/release/generate-release.sh
Currently we have the following CI issues [knative-nightly-ci-eventing-kafka-broker/185/console](https://master-jenkins-csb-serverless-qe.apps.ocp-c1.prod.psi.redhat.com/job/ci/job/knative-nightly-ci-eventing-kafka-broker/185/console): 
```
01:42:50  vendor/knative.dev/eventing/test/rekt/resources/eventlibrary vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml registry.ci.openshift.org/openshift/knative-eventing-kafka-broker knative-nightly true
01:42:50  Writing resolved yaml to vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/eventlibrary.yaml knative-nightly
01:42:50  Resolving vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/*.yaml
01:42:50  sed: can't read vendor/knative.dev/eventing/test/rekt/resources/eventlibrary/*.yaml: No such …
```
> Remove eventlibrary from rekt image replaces

- openshift/ci-operator/generate-dockerfiles.sh
Cleanup target dir for Dockerfiles before generating them to have a clean start.
> Remove target dir for Dockerfiles before creating them

- Makefile
We don't need to copy the dispatcher & receiver images as we then end up with the same Dockerfiles at two different places. So we simply keep them at the static-images folder.
> Don't copy static-images to knative-images

- control-plane/pkg/reconciler/consumergroup/controller.go
- openshift/e2e-common.sh
- openshift/e2e-rekt-tests.sh
- openshift/patches/fix_scheduler_and_autoscaler_scale_down_delay.patch
- openshift/release/generate-release.sh
- test/e2e_new/features/kafka_source.go
- test/e2e_new/kafka_source_test.go
- vendor/knative.dev/eventing/pkg/scheduler/state/state.go
- vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go
- vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
Introduce a scale down delay so that the scaling down is more
consistent and converges to a specific number of replicas
(similar to how it was before)
Improve autoscaler state logging
> [SRVKE-1400] Autoscaler improvements

- openshift/ci-operator/Dockerfile.in
stashing the UBI change on `main` for future (1.9+) branch creation
> using UBI and nonroot user

- openshift/patches/remove_seccomp_profile.patch
Current CI issue:
```
01:34:12  error: patch failed: data-plane/config/brokerv2/500-dispatcher.yaml:153
01:34:12  error: data-plane/config/brokerv2/500-dispatcher.yaml: patch does not apply
```
Changes on `brokerv2/500-dispatcher.yaml` were introduced in https://github.com/knative-sandbox/eventing-kafka-broker/pull/2977
> Update patch to remove seccomp profiles

- openshift/e2e-common.sh
- openshift/release/generate-release.sh
* Event-flaker image was removed in https://github.com/knative/eventing/pull/6750 and in CI in https://github.com/openshift/release/pull/36826.
* Additionally this PR cleans up a leftover from the event-library removal from https://github.com/openshift-knative/eventing-kafka-broker/pull/586
> Remove event flaker test image

- openshift/e2e-common.sh
Remove the e2e tests running in the test/e2e_broker directory as the directory was removed in
https://github.com/knative-sandbox/eventing-kafka-broker/pull/3004
See issues e.g. in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_eventing-kafka-broker/631/pull-ci-openshift-knative-eventing-kafka-broker-release-next-412-test-e2e-aws-ocp-412/1635080131514994688
> Remove e2e tests on `test/e2e_broker` directory

- openshift/patches/use_quay_images.patch
Based on upstream bump PR (3041), this script needs to be adjusted
**NOTE:** this is not about discussing the version, it's about correcting the changed `ko://` path that will be replaced.
> Update the test script due to recent bump

- openshift/ci-operator/build-image/Dockerfile
We have some cache issues, since we updated to Go 1.19:
```
github.com/openshift-knative/serverless-operator/hack imports
knative.dev/pkg/hack: open /go/.cache/39/392806b81c87ffe152fa7bcfd4abfdffdab0dbfae1a3d12b20605770c0f60b73-d: permission denied
```
This is, because "we" create the `$GOPATH/.cache` directory as root and later try to access it as the runtime user from openshift-ci.
As we don't really need the `.cache` directory, we can remove it in the build image.
> Remove .cache directory in build-image Dockerfile to avoid permission issues with Go 1.19

- openshift/release/artifacts/eventing-kafka-broker.yaml
- openshift/release/artifacts/eventing-kafka-channel.yaml
- openshift/release/artifacts/eventing-kafka-controller.yaml
- openshift/release/artifacts/eventing-kafka-post-install.yaml
- openshift/release/artifacts/eventing-kafka-sink.yaml
- openshift/release/artifacts/eventing-kafka-source.yaml
- openshift/release/artifacts/eventing-kafka.yaml
- openshift/release/resolve.sh
We changed the label to `app.kubernetes.io/version` from `kafka.eventing.knative.dev/release`
> [release-v1.9] Change version label

- Makefile
The TEST_IMAGES variable is used for building multiarch image via Github action.
> [release-v1.8] Add logs-exporter and watch-cm test images

- data-plane/THIRD-PARTY.txt
- data-plane/core/pom.xml
Backport https://github.com/knative-sandbox/eventing-kafka-broker/commit/725c45db2c3949c654bbf20482bc79179110049f
> SRVKE-1463: [release-v1.8] Exclude slf4j-jboss-logmanager from quarkus-vertx for logging (#2934)

- test/e2e_new/main_test.go
- test/rekt/resources/configmap/broker/broker_config.go
- test/rekt/resources/configmap/broker/broker_config.yaml
This is a backport of [upstream commit](https://github.com/knative-sandbox/eventing-kafka-broker/commit/2973309cf3c34877059a956b28d7a734e84ecf76) which was supposed to get to midstream automatically but somehow didn't get there. 
This is required for finishing https://github.com/openshift-knative/serverless-operator/pull/2065
> [release-v1.9] Conformance tests against MTChannelBasedBroker

- test/e2e_new/broker_conformance_test.go
This test can run multiple times for different implementations and also in a common namespace. The name must be unique for each run.
This is a backport of upstream fix.
> Unique broker name in broker conformance tests

- openshift/release/generate-release.sh
Seems the removed `override-min-version.patch` (from #709 ) was used in `generate-release.sh` too.
> Remove leftover from version patch removal

- openshift/ci-operator/static-images/dispatcher/Dockerfile
- openshift/ci-operator/static-images/receiver/Dockerfile
In https://github.com/knative-sandbox/eventing-kafka-broker/pull/3106 the dispatcher-vertx and receiver-vertx modules were added.
Should fix the CI issues from https://github.com/openshift-knative/eventing-kafka-broker/pull/705 (at least the image builds)
> Add vertx modules of dispatcher and receiver

- openshift/ci-operator/static-images/receiver/Dockerfile
In https://github.com/knative-sandbox/eventing-kafka-broker/pull/3142 the receiver was split into the vertx and (for later loom) module. The vertx receiver is now available in the receiver-vertx module. This PR updates the dockerfile to use the receiver-vertx module.
CI issues from https://github.com/openshift-knative/eventing-kafka-broker/pull/718:
in receiver pod:
```
no main manifest attribute, in /app/app.jar
```
> Use vertx module of receiver

- openshift/ci-operator/static-images/dispatcher/Dockerfile
In https://github.com/knative-sandbox/eventing-kafka-broker/pull/3177 we switched to the dispatcher-vertx module
> Use vertx module of dispatcher

- test/e2e_new/broker_conformance_test.go
It might take longer than default 2 minutes to finish the tests and since all the steps run in parallel now the time starts to tick earlier.
Backport from upstream.
> Increase PollTimings for TestBrokerConformance

- openshift/ci-operator/static-images/dispatcher/Dockerfile
- openshift/ci-operator/static-images/receiver/Dockerfile
We get build errors in CI (#737) due to the missing modules which are referenced in the poms:
```
INFO[2023-07-15T00:48:04Z] Build knative-eventing-kafka-broker-dispatcher failed, printing logs: 
...
[1/2] STEP 2/17: ENV "BUILD_LOGLEVEL"="0"
[1/2] STEP 3/17: WORKDIR /build
[1/2] STEP 4/17: COPY /data-plane/pom.xml .
[1/2] STEP 5/17: COPY /data-plane/.editorconfig .
[1/2] STEP 6/17: COPY /data-plane/core/pom.xml core/pom.xml
[1/2] STEP 7/17: COPY /data-plane/receiver/pom.xml receiver/pom.xml
[1/2] STEP 8/17: COPY /data-plane/receiver-vertx/pom.xml receiver-vertx/pom.xml
[1/2] STEP 9/17: COPY /data-plane/dispatcher/pom.xml dispatcher/pom.xml
[1/2] STEP 10/17: COPY /data-plane/dispatcher-vertx/pom.xml dispatcher-vertx/pom.xml
[1/2] STEP 11/17: COPY /data-plane/contract/pom.xml …
```
> Add loom modules

- openshift/patches/unique-secret-names.patch
- test/rekt/features/broker_deleted_recreated.go
- test/rekt/features/featuressteps/copy_secret.go
- test/rekt/features/kafka_source.go
- test/rekt/features/kafka_source_create_secrets_after.go
- vendor/knative.dev/eventing/pkg/utils/secret.go
Backport from upstream.
*   Includes changes in vendor directory for knative/eventing and the patch that creates the changes if applied.
> [release-v1.10] Unique secret names

- openshift/release/mirror-upstream-branches.sh
- openshift/release/update-to-head.sh
We used to not have this for this repository, I believe it's now time for having it
- copied working file from eventing-core midstream (https://github.com/openshift-knative/eventing/blob/main/openshift/release/mirror-upstream-branches.sh)
- call file in update-to-head.sh
> [main] Mirror upstream branches

- openshift/patches/add-eventshub-port-name.patch
- openshift/release/artifacts/eventing-kafka-controller.yaml
- openshift/release/artifacts/eventing-kafka.yaml
- openshift/release/generate-release.sh
- vendor/knative.dev/reconciler-test/pkg/eventshub/102-service.yaml
Same as https://github.com/openshift-knative/eventing/pull/289
> [release-v1.10] Add eventshub service port name

- data-plane/pom.xml
using newer version of snappy (`1.1.10.1`), instead of ` 1.1.8.4`.
Release notes of that version: https://github.com/xerial/snappy-java/releases/tag/v1.1.10.1
FWIW, the Quarkus team uses now exactly this too:
https://github.com/quarkusio/quarkus/blob/1a6227669a2a294fb0083e43469a7ef78ca16dba/bom/application/pom.xml#L151 
run `mvn dependency:tree` to see it lists the above mentioned version
> Update snappy to latest by explicitly list it as a dependency

- control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_types.go
Fixes https://issues.redhat.com/browse/SRVKE-1508
This fix should be necessary only for `release-v1.9` branch because that's where SecretSpec is added. For 1.10 and later the webhook will not complain about the field.
We could port this change to newer branches to get rid of `SecretSpec: null` which doesn't hurt but it's redundant.
> [release-v1.9] Make SecretSpec field of consumers Auth optional

- control-plane/pkg/reconciler/consumergroup/auth.go
- control-plane/pkg/reconciler/consumergroup/autoscaler_config.go
- control-plane/pkg/reconciler/consumergroup/consumergroup.go
- control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
- control-plane/pkg/reconciler/consumergroup/evictor.go
- control-plane/pkg/reconciler/consumergroup/evictor_test.go
- go.mod
Cherry-pick https://github.com/knative-extensions/eventing-kafka-broker/pull/3294
> [release-v1.9] Expose init offset and schedule metrics for ConsumerGroup reconciler

- control-plane/pkg/reconciler/consumergroup/auth.go
- control-plane/pkg/reconciler/consumergroup/autoscaler_config.go
- control-plane/pkg/reconciler/consumergroup/consumergroup.go
- control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
- control-plane/pkg/reconciler/consumergroup/evictor.go
- control-plane/pkg/reconciler/consumergroup/evictor_test.go
- go.mod
Manual CP of https://github.com/openshift-knative/eventing-kafka-broker/pull/790
> [release-v1.10] Expose init offset and schedule metrics for ConsumerGroup reconciler (#790)

- control-plane/pkg/reconciler/consumergroup/consumergroup.go
- control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
- control-plane/pkg/reconciler/consumergroup/controller.go
- openshift/patches/autoscaler_leader_log.patch
- openshift/patches/remove_resource_version_check.patch
- openshift/release/generate-release.sh
- vendor/knative.dev/eventing/pkg/scheduler/statefulset/autoscaler.go
- vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
When there is high load and multiple consumer groups are created and reconciled, we get many `dial tcp 10.130.4.8:9092: i/o timeout` errors when trying to connect to Kafka.
This leads to increased "time to readiness" for consumer groups.
The downside of caching is that, in the rare case, partitions increase while the result is cached we won't initialize the offsets of the new partitions.
It's based on the existing prober cache
> SRVKE-958: [release-v1.9] Cache init offsets results

- openshift/patches/handle_overcommitted_pods.patch
- vendor/knative.dev/eventing/pkg/scheduler/state/state.go
- vendor/knative.dev/eventing/pkg/scheduler/statefulset/scheduler.go
This patch will handle these 2 other cases:
```golang
{
name:      "two replicas, 12 vreplicas, already scheduled on overcommitted pod, remove replicas",
vreplicas: 12,
replicas:  int32(2),
placements: []duckv1alpha1.Placement{
{PodName: "statefulset-name-0", VReplicas: 12},
},
expected: []duckv1alpha1.Placement{
{PodName: "statefulset-name-0", VReplicas: 10},
{PodName: "statefulset-name-1", VReplicas: 2},
},
schedulerPolicyType: scheduler.MAXFILLUP,
},
{
name:      "one replica, 12 vreplicas, already scheduled on overcommitted pod, remove replicas",
vreplicas: 12,
replicas:  int32(1),
placements: []duckv1alpha1.Placement{
{PodName: "statefulset-name-0", VReplicas: 12},
},
expected: []duckv1alpha1.Placement{
{PodName: "statefulset-name-0", VReplicas: 10},
},
err: …
```
> [release-v1.9] Scheduler handles overcommitted pods

- test/keda-reconciler-tests.sh
- test/keda/enable-keda-autoscaling.yaml
Backport of https://github.com/knative-extensions/eventing-kafka-broker/pull/3322
> [release-v1.11] Add script to run KafkaSource tests with KEDA (#3322)

- data-plane/pom.xml
similar to https://github.com/openshift-knative/eventing-kafka-broker/pull/843 but adding the actual override (as done in https://github.com/openshift-knative/eventing-kafka-broker/pull/772)
> [release-v1.11] Update snappy override to latest

- openshift/knative-eventing.yaml
The `new-trigger-filter` FF was enabled in upstream in https://github.com/knative/eventing/pull/7243. We should enable it for our tests as well.
Test on release next: https://github.com/openshift-knative/eventing-kafka-broker/pull/853
> Enable new-trigger-filter feature flag

- openshift/e2e-common.sh
In SO CI the permission error will fail the test, so we need to skip in when running tests in that repository.
This is an example https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/2310/pull-ci-openshift-knative-serverless-operator-main-4.13-upstream-e2e-kafka-aws-ocp-413/1713907700934381568
Besides that, in that repository, the command is not necessary
> [release-v1.11] Allow skipping make generate-release in e2e_new_tests

- openshift/e2e-common.sh
In https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_serverless-operator/2310/pull-ci-openshift-knative-serverless-operator-main-4.13-upstream-e2e-kafka-aws-ocp-413/1714590471239503872 I'm getting 
```
cat: /go/src/knative.dev/eventing-kafka-broker/test/images.yaml: No such file or directory
```
because it using the wrong directory and as described here this the more resilient way of doing this https://stackoverflow.com/questions/59895/how-do-i-get-the-directory-where-a-bash-script-is-located-from-within-the-script
> [release-v1.11] Improve getting the script directory

- control-plane/pkg/reconciler/consumergroup/consumergroup.go
Cherry-pick of https://github.com/knative-extensions/eventing-kafka-broker/commit/9ef55f261173f98800a256eb9b94aa4d35453f81
> [release-v1.11] Add metrics to monitor the ConsumerGroup replicas changes (#3386)

- go.mod
- go.sum
- vendor/knative.dev/pkg/webhook/webhook.go
- vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
- vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
- vendor/knative.dev/reconciler-test/pkg/feature/feature.go
- vendor/knative.dev/reconciler-test/pkg/feature/logging.go
- vendor/modules.txt
Basicially this PR just runs:
```
./hack/update-deps.sh --upgrade --release 1.10
```
followed by `make RELEASE...`
> [release-v1.11] HTTP/2 disable patch from upstream

- go.mod
- go.sum
- vendor/knative.dev/pkg/webhook/webhook.go
- vendor/knative.dev/reconciler-test/pkg/environment/namespace.go
- vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/100-sa.yaml
- vendor/knative.dev/reconciler-test/pkg/eventshub/rbac/rbac.go
- vendor/knative.dev/reconciler-test/pkg/feature/feature.go
- vendor/knative.dev/reconciler-test/pkg/feature/logging.go
- vendor/modules.txt
Basicially this PR just runs:
```
./hack/update-deps.sh --upgrade --release 1.10
```
followed by `make RELEASE...`
> [release-v1.10] HTTP/2 disable patch from upstream

- openshift/patches/011-http2-cve.patch
- openshift/release/generate-release.sh
- vendor/knative.dev/pkg/webhook/webhook.go
Manually updated the `webhook.go` file to make it match to upstream's PR (https://github.com/knative/pkg/commit/b8c14ce9f90321c5a13ee5a41838a342343cc028)
> [release-v1.9] HTTP/2 disable patch from upstream

- openshift/patches/namespaced_broker_copy_trustedca_cm.patch
Currently some namespace broker e2e tests [fail](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift-knative_eventing-kafka-broker/905/pull-ci-openshift-knative-eventing-kafka-broker-release-next-413-test-reconciler-aws-ocp-413/1732199568130445312), as the kafka-broker-receiver pod does not come up due to:
```
{
"apiVersion": "v1",
"count": 1,
"eventTime": null,
"firstTimestamp": "2023-12-06T02:00:20Z",
"involvedObject": {
"apiVersion": "v1",
"kind": "Pod",
"name": "kafka-broker-dispatcher-5497cb57c7-nm7mn",
"namespace": "test-mszpfxqr",
"resourceVersion": "223646",
"uid": "6d6556f8-85b8-420f-a9b1-31b9a0a8cc31"
},
"kind": "Event",
"lastTimestamp": "2023-12-06T02:00:20Z",
"message": "MountVolume.SetUp failed for volume \"config-openshift-trusted-cabundle-volume\" : …
```
> Add patch to copy openshift-trusted-cabundle CM to namespaced broker namespace

- test/e2e_new/broker_test.go
to workaround flaking TestKafkaSourceDeletedFromContractConfigMaps
> Increase hardcoded PollTimeout value to 8m

- control-plane/config/eventing-kafka-broker/100-channel/100-kafka-channel.yaml
- control-plane/pkg/prober/async_prober.go
- control-plane/pkg/prober/async_prober_test.go
- control-plane/pkg/prober/composite_prober.go
- control-plane/pkg/prober/composite_prober_test.go
- control-plane/pkg/prober/prober.go
- control-plane/pkg/prober/prober_test.go
- control-plane/pkg/prober/probertesting/mock_prober.go
- control-plane/pkg/prober/probertesting/mock_prober_test.go
- control-plane/pkg/reconciler/broker/broker.go
- control-plane/pkg/reconciler/channel/channel.go
- control-plane/pkg/reconciler/channel/channel_test.go
- control-plane/pkg/reconciler/channel/controller.go
- control-plane/pkg/reconciler/channel/controller_test.go
- control-plane/pkg/reconciler/channel/resources/service.go
- control-plane/pkg/reconciler/channel/v2/channelv2.go
- control-plane/pkg/reconciler/channel/v2/channelv2_test.go
- control-plane/pkg/reconciler/channel/v2/controllerv2.go
- control-plane/pkg/reconciler/sink/controller.go
- control-plane/pkg/reconciler/sink/kafka_sink.go
- control-plane/pkg/reconciler/sink/kafka_sink_test.go
- control-plane/pkg/reconciler/testing/objects_channel.go
- test/e2e_new/channel_eventing_tls_test.go
- test/rekt/features/channel_tls.go
- test/rekt/resources/kafkachannel/kafkachannel.go
Cherry-pick https://github.com/knative-extensions/eventing-kafka-broker/pull/3406/files
> [release-v1.11] Cherry-pick E2E tests for channel: TLS key pair rotation #3406

- openshift/ci-operator/static-images/dispatcher/Dockerfile
- openshift/ci-operator/static-images/receiver/Dockerfile
Use the ubi9 openjdk-21 images as base images for the builder and runtime.
Hint:
* Need to switch to the root user for the maven build in f436dfc53cc0b08f12b6398a065d8dab4d0ae61a (the previous used `quay.io/openshift-knative/17-jdk-centos7` image run under root too):
```
$ docker run --rm -it quay.io/openshift-knative/17-jdk-centos7:latest id
uid=0(root) gid=0(root) groups=0(root)
```
Test run in https://github.com/openshift-knative/eventing-kafka-broker/pull/928
> Use ubi9 jdk 21 base images for dispatcher & receiver

- openshift/patches/reconciler-test-delete-resources-timeout-increase.patch
- vendor/knative.dev/reconciler-test/pkg/feature/feature.go
workaround for TestKafkaSourceDeletedFromContractConfigMaps timeouts on cleanup
on 1.11 we backported reconciler-test https://github.com/openshift-knative/eventing-kafka-broker/commit/8feed0c277afd4a303ce52ade6d3420eb9c545e8 , but let's keep a simpler patch for 1.10
> 1.10 reconciler timeouts backport

- hack/update-codegen.sh
- openshift/e2e-common.sh
- openshift/patches/chmod-codegen.patch
- openshift/release/generate-release.sh
- vendor/knative.dev/hack/codegen-library.sh
This is similar to [PR for release-v1.11](https://github.com/openshift-knative/eventing-kafka-broker/pull/884).
The required [upstream change](https://github.com/knative/hack/commit/d4af42e9b2225f807d75066f3b377c880646f003) was not backported to release-1.12 branch so we still need to have this downstream patch.
This fixes issues like this:
```
make[1]: Entering directory `/go/src/github.com/openshift-knative/eventing-kafka-broker'
./openshift/release/generate-release.sh 
chmod: changing permissions of './vendor/k8s.io/code-generator/generate-groups.sh': Operation not permitted 
```
This change also includes calling update_cert_manager.sh via bash directly, another backport from upstream.
> [release-v1.12] Patch for chmod on codegen files

- data-plane/THIRD-PARTY.txt
- data-plane/pom.xml
This reverts commit a0c2dea9f1dc69b13140c1eef524984926be556e **_AND_** goes to latest of `1.2.x` of logback
> [release-v1.11] Revert 'logger bump' backport from upstream/main and go to latest 1.2.x logback

- test/rekt/features/broker_config.go
Backport from upstream.
When running many tests in parallel, waiting for the Topic might start much earlier than creating the Broker/Topic and it can time out (see below). This change ensures that waiting for the topic starts later.
```
=== CONT
TestBrokerWithConfig/Broker_KafkaTopic_config_from_Broker_configmap/Setup/Topic_is_ready
wait.go:136: kafka knative-broker-test-msvvevxa-broker-dtbsqwrn not
found kafkatopics.kafka.strimzi.io
"knative-broker-test-msvvevxa-broker-dtbsqwrn" not found
topic.go:73: kafka.strimzi.io/v1beta2, Resource=kafkatopics did not
become ready, timed out waiting for the condition
```
> TestBrokerWithConfig waits for Topic in Requirement phase

- go.mod
- go.sum
- openshift/ci-operator/build-image/Dockerfile
- openshift/ci-operator/knative-images/event_display/Dockerfile
- openshift/ci-operator/knative-images/heartbeats/Dockerfile
- openshift/ci-operator/knative-images/kafka-controller/Dockerfile
- openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile
- openshift/ci-operator/knative-images/migrate/Dockerfile
- openshift/ci-operator/knative-images/post-install/Dockerfile
- openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
- openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
- openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
- openshift/ci-operator/knative-test-images/event-sender/Dockerfile
- openshift/ci-operator/knative-test-images/eventshub/Dockerfile
- openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
- openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile
- openshift/ci-operator/knative-test-images/performance/Dockerfile
- openshift/ci-operator/knative-test-images/print/Dockerfile
- openshift/ci-operator/knative-test-images/recordevents/Dockerfile
- openshift/ci-operator/knative-test-images/request-sender/Dockerfile
- openshift/ci-operator/knative-test-images/watch-cm/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
- openshift/release/artifacts/eventing-kafka-controller.yaml
- openshift/release/artifacts/eventing-kafka.yaml
Related to https://github.com/openshift-knative/serverless-operator/pull/2451
> [release-v1.12] Bump to Go v1.21

- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleBuilder.java
workloads now have `subPath` injection, so all files are just on the `/ocp-serverless-custom-certs` directory
/hold
depends on https://github.com/openshift-knative/serverless-operator/pull/2422
> [release-v1.11] Cert injection, rely on workload's subPath injection

- data-plane/THIRD-PARTY.txt
- data-plane/pom.xml
same like #938, but for `release-v1.10` branch
> [release-v1.10] Updating logback-core to latest 1.12.x

- control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-features.yaml
- control-plane/pkg/apis/config/features.go
- openshift/ci-operator/build-image/Dockerfile
- openshift/ci-operator/knative-images/event_display/Dockerfile
- openshift/ci-operator/knative-images/heartbeats/Dockerfile
- openshift/ci-operator/knative-images/kafka-controller/Dockerfile
- openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile
- openshift/ci-operator/knative-images/migrate/Dockerfile
- openshift/ci-operator/knative-images/post-install/Dockerfile
- openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
- openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
- openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
- openshift/ci-operator/knative-test-images/event-sender/Dockerfile
- openshift/ci-operator/knative-test-images/eventshub/Dockerfile
- openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
- openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile
- openshift/ci-operator/knative-test-images/performance/Dockerfile
- openshift/ci-operator/knative-test-images/print/Dockerfile
- openshift/ci-operator/knative-test-images/recordevents/Dockerfile
- openshift/ci-operator/knative-test-images/request-sender/Dockerfile
- openshift/ci-operator/knative-test-images/watch-cm/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
- openshift/ci-operator/source-image/Dockerfile
- openshift/release/artifacts/eventing-kafka-controller.yaml
- openshift/release/artifacts/eventing-kafka.yaml
Backport of https://github.com/knative-extensions/eventing-kafka-broker/commit/930a91b33e5c22b62b7affb5d9cb2301a7f4e078
> [release-v1.11] Rename config-kafka-features feature flags to be consistent with eventing core feature flag names (#3512)

- control-plane/pkg/kafka/testing/admin_mock.go
- control-plane/pkg/reconciler/trigger/trigger.go
- control-plane/pkg/reconciler/trigger/trigger_test.go
This is the non breaking change related to https://github.com/knative-extensions/eventing-kafka-broker/commit/bfeb3c39f741b8380788cd573bff499c59834e47
> [release-v1.11] Backport fix for random consumer group id access

- openshift/e2e-common.sh
This is now present in SO as part os `install-kafka*`, so we don't need it here anymore
> [release-v1.11] Remove cert-manager setup, use the one in SO

- control-plane/pkg/reconciler/trigger/controller.go
The current global resync accidently queues triggers that aren't associated with our brokers.
> [release-v1.11] Use filtered global resync for triggers (#3678)

- openshift/release/generate-release.sh
Currently we have the following issue in our update-to-head Jenkins job:
```
01:44:45  Resolving data-plane/config/channel-tls/channel-ingress-tls-certificate.yaml
01:44:45  data-plane/config/sink-tls openshift/release/artifacts/eventing-kafka-tls-networking.yaml registry.ci.openshift.org/openshift/knative-eventing-kafka-broker knative-nightly
01:44:45  Writing resolved yaml to openshift/release/artifacts/eventing-kafka-tls-networking.yaml nightly
01:44:45  Resolving data-plane/config/sink-tls/sink-ingress-tls-certificate.yaml
01:44:45  control-plane/config/post-install openshift/release/artifacts/eventing-kafka-post-install.yaml registry.ci.openshift.org/openshift/knative-eventing-kafka-broker
01:44:45  ./openshift/release/resolve.sh: line 9: $4: unbound variable
01:44:45  make: *** …
```
> Add missing param to `resolve_resources` call

- control-plane/pkg/client/internals/kafka/informers/externalversions/factory.go
- openshift/ci-operator/build-image/Dockerfile
- openshift/ci-operator/knative-images/event_display/Dockerfile
- openshift/ci-operator/knative-images/heartbeats/Dockerfile
- openshift/ci-operator/knative-images/kafka-controller/Dockerfile
- openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile
- openshift/ci-operator/knative-images/migrate/Dockerfile
- openshift/ci-operator/knative-images/post-install/Dockerfile
- openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
- openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
- openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
- openshift/ci-operator/knative-test-images/event-sender/Dockerfile
- openshift/ci-operator/knative-test-images/eventshub/Dockerfile
- openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
- openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile
- openshift/ci-operator/knative-test-images/performance/Dockerfile
- openshift/ci-operator/knative-test-images/print/Dockerfile
- openshift/ci-operator/knative-test-images/recordevents/Dockerfile
- openshift/ci-operator/knative-test-images/request-sender/Dockerfile
- openshift/ci-operator/knative-test-images/watch-cm/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
Running plain `Running 'make RELEASE=v1.13 generate-release'` gives these changes.
They are matching w/ `release-next` branch
> [release-v1.13] Running 'make RELEASE=v1.13 generate-release'

- openshift/e2e-common.sh
try with -parallel 64 to deal with a possible starvation in TestBrokerWithManyTriggers
> [release-v1.13] try to run new_tests with parallel 64

- openshift/e2e-common.sh
backport https://github.com/openshift-knative/eventing-kafka-broker/pull/1017
> [release-v1.11] backport running new_tests with parallel 64

- openshift/knative-eventing.yaml
The eventtype autocreate feature (and tests) were added in upstream in https://github.com/knative-extensions/eventing-kafka-broker/pull/3585.
So we should enable it for our tests as well.
Test run in release-next in #1027
Should also help with #1002
/hold
to wait for the test results in #1027
> Enable eventtype-auto-create feature flag

- openshift/patches/namespaced_broker_copy_trustedca_cm.patch
As per title to fix Jenkins job:
https://master-jenkins-csb-serverless-qe.apps.ocp-c1.prod.psi.redhat.com/job/ci/job/knative-nightly-ci-eventing-kafka-broker/629/console
```
00:07:02.771  Checking patch control-plane/pkg/reconciler/broker/namespaced_broker.go...
00:07:02.771  error: while searching for:
00:07:02.771  		"config-kafka-broker-data-plane",
00:07:02.771  		"config-tracing",
00:07:02.771  		"kafka-config-logging",
00:07:02.771  	}
00:07:02.771  	resources := make([]unstructured.Unstructured, 0, len(configMaps))
00:07:02.771  	for _, name := range configMaps {
00:07:02.771  
00:07:02.771  error: patch failed: control-plane/pkg/reconciler/broker/namespaced_broker.go:386
00:07:02.771  error: control-plane/pkg/reconciler/broker/namespaced_broker.go: patch does not apply
```
> Update namespaced broker CA bundle patch

- test/e2e_new/broker_sasl_ssl_test.go
- test/kafka/kafka_setup.sh
- test/kafka/user-sasl-scram-512-restricted.yaml
- test/pkg/run.go
- test/rekt/features/broker_auth.go
- test/rekt/resources/kafkaauthsecret/kafkaauthsecret.go
Backport of upstream #3766 to our midstream
> [release-v1.12] e2e test for broker topic and trigger consumer id templates being used

- control-plane/pkg/reconciler/consumergroup/consumergroup.go
- control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
- control-plane/pkg/reconciler/consumergroup/controller.go
A manual backport of https://github.com/knative-extensions/eventing-kafka-broker/pull/3775
This is needed so that in the next release, we don't have the kafka controller CrashLoopBackoff from panics
> [release-v1.12] Avoid possible nil pointer dereferences in consumergroup scheduling

- data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/AuthProvider.java
- data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KubernetesAuthProvider.java
- data-plane/core/src/test/java/dev/knative/eventing/kafka/broker/core/security/KubernetesAuthProviderTest.java
- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/Main.java
- data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
Fix errors like:
```
\"io.vertx.core.Vertx.currentContext()\" is null\n\tat dev.knative.eventing.kafka.broker.core.security.KubernetesAuthProvider.getCredentials(KubernetesAuthProvider.java:38)
```
> [release-v1.12] Remove usage of Vertx.currentContext()

- control-plane/pkg/core/config/utils.go
- control-plane/pkg/reconciler/broker/broker.go
- control-plane/pkg/reconciler/channel/channel.go
- control-plane/pkg/reconciler/consumer/consumer.go
- control-plane/pkg/reconciler/sink/kafka_sink.go
Backport of https://github.com/openshift-knative/eventing-kafka-broker/pull/999 to here
> [release-v1.12] Detect trust bundles changes

- openshift/patches/remove_seccomp_profile.patch
Adjusting seccomp patch:
* for `data-plane/config/broker/500-receiver.yaml` after https://github.com/knative-extensions/eventing-kafka-broker/pull/3852/files
* for `data-plane/config/brokerv2/500-dispatcher.yaml` after https://github.com/knative-extensions/eventing-kafka-broker/pull/3823/files
Jenkins failure: https://master-jenkins-csb-serverless-qe.apps.ocp-c1.prod.psi.redhat.com/job/ci/job/knative-nightly-ci-eventing-kafka-broker/675/console
> Adjust seccomp patch to latest receiver.yaml changes

- data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/IngressProducerReconcilableStore.java
Cherry-pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/3875/files
> [release-v1.12] Use ConcurrentHashMap in IngressProducerReconcilableStore to avoid ConcurrentModificationException

- control-plane/pkg/contract/extensions.go
- control-plane/pkg/core/config/egress.go
- control-plane/pkg/core/config/egress_test.go
- control-plane/pkg/core/config/resource.go
- control-plane/pkg/core/config/resource_test.go
- control-plane/pkg/reconciler/base/reconciler.go
- control-plane/pkg/reconciler/base/reconciler_test.go
- control-plane/pkg/reconciler/broker/broker.go
- control-plane/pkg/reconciler/channel/channel.go
- control-plane/pkg/reconciler/channel/v2/channelv2.go
- control-plane/pkg/reconciler/consumer/consumer.go
- control-plane/pkg/reconciler/sink/kafka_sink.go
- control-plane/pkg/reconciler/trigger/trigger.go
- control-plane/pkg/reconciler/trigger/trigger_test.go
Cherry-pick of https://github.com/knative-extensions/eventing-kafka-broker/commit/483904b1ef984bdf792dbeba571fda04e5db0963
> [release-v1.14] Prevent generation only updates (#3915)

- openshift/generate.sh
> go get is no longer supported outside of a module in the legacy GOPATH mode (that is, with GO111MODULE=off). Other build commands, such as go build and go test, will continue to work indefinitely for legacy GOPATH programs.
from 1.22 release notes: https://tip.golang.org/doc/go1.22
Should fix https://master-jenkins-csb-serverless-qe.apps.ocp-c1.prod.psi.redhat.com/job/ci/job/knative-nightly-ci-eventing-kafka-broker/732/console
> Switch to go install to install hack/generate

- openshift/generate.sh
Same as openshift-knative/eventing/pull/657 but for EKB
> Use OCP 4.17 based image in generate to support Go 1.22

- control-plane/pkg/autoscaler/keda/keda.go
- test/e2e_new/kafka_source_test.go
- test/rekt/features/keda_scaling.go
A backport of https://github.com/knative-extensions/eventing-kafka-broker/pull/3941 to fix errors on KEDA scaled objects when there is no need for an authentication reference
> [release-v1.14] fix: only add triggerAuth to scaled objects when there is an actual value to reference (#3941)

- control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation.go
- control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation_test.go
- control-plane/pkg/reconciler/consumergroup/consumergroup.go
Cherry-pick of https://github.com/knative-extensions/eventing-kafka-broker/commit/12d1f32b144ed50ad4eea3f6ed00bac6128c2b05
* fix: kafka controller does not panic on invalid kafka client config
* fix: consumergroup configs are validated as non-nil
> [release-v1.14] fix: kafka controller does not panic on invalid kafka client config (#4002)

- go.mod
- openshift/ci-operator/build-image/Dockerfile
- openshift/ci-operator/knative-images/event_display/Dockerfile
- openshift/ci-operator/knative-images/heartbeats/Dockerfile
- openshift/ci-operator/knative-images/kafka-controller/Dockerfile
- openshift/ci-operator/knative-images/kafka-source-controller/Dockerfile
- openshift/ci-operator/knative-images/migrate/Dockerfile
- openshift/ci-operator/knative-images/post-install/Dockerfile
- openshift/ci-operator/knative-images/webhook-kafka/Dockerfile
- openshift/ci-operator/knative-test-images/committed-offset/Dockerfile
- openshift/ci-operator/knative-test-images/consumer-group-lag-provider-test/Dockerfile
- openshift/ci-operator/knative-test-images/event-sender/Dockerfile
- openshift/ci-operator/knative-test-images/eventshub/Dockerfile
- openshift/ci-operator/knative-test-images/kafka-consumer/Dockerfile
- openshift/ci-operator/knative-test-images/logs-exporter/Dockerfile
- openshift/ci-operator/knative-test-images/performance/Dockerfile
- openshift/ci-operator/knative-test-images/print/Dockerfile
- openshift/ci-operator/knative-test-images/recordevents/Dockerfile
- openshift/ci-operator/knative-test-images/request-sender/Dockerfile
- openshift/ci-operator/knative-test-images/watch-cm/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-fetcher/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-forwarder/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-receiver/Dockerfile
- openshift/ci-operator/knative-test-images/wathola-sender/Dockerfile
- openshift/generate.sh
Not really sure what I am doing, but IIUC, SO 1.34 will use go 1.22, so we need to update eventing 1.14 to go 1.22
(as that's currently failing https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-knative-eventing-kafka-broker-release-v1.14-412-test-e2e-aws-412-c/1820646135702753280 
./hack/update-deps.sh
invalid value "1.22" for flag -compat: maximum supported Go version is 1.21.11 
)
> [release-v1.14] update to golang 1.22

- control-plane/config/post-install/200-controller-cluster-role.yaml
This is a cherry pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/4022 to make sure that the post install job has the correct permissions
> [release-v1.14] fix: correct clusterrole permissions (#4022)

- control-plane/pkg/reconciler/trigger/v2/triggerv2.go
- control-plane/pkg/reconciler/trigger/v2/triggerv2_test.go
This is a cherry pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/4046 to remove the finalizer when a trigger is deleted
> [release-v1.15] Remove finalizer when trigger is deleted (#4046)

- control-plane/pkg/reconciler/channel/controller.go
Fix for panic
```
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1f9a4c0, 0x3a9fbb0})
/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000ec6380?})
/go/src/github.com/openshift/origin/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x1f9a4c0?, 0x3a9fbb0?})
/usr/lib/golang/src/runtime/panic.go:770 +0x132
knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/channel.NewController.HandleAll.PassNew.func12({0x4?, 0x23?}, {0x22c8200?, 0xc0033a2000?})
/go/src/github.com/openshift/origin/vendor/knative.dev/pkg/controller/controller.go:76 +0x1c
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...) …
```
> Set globalResync function for KafkaChannel reconciler

- Makefile
In #1132 we see 
```
sh openshift/e2e-rekt-tests.sh
/go/src/github.com/openshift-knative/eventing-kafka-broker/test/../vendor/knative.dev/hack/library.sh: line 184: `log.step': not a valid identifier
make: *** [Makefile:39: test-reconciler] Error 2
```
This is, as `log.step` is not a valid identifier in shell. Change came in via https://github.com/knative-extensions/eventing-kafka-broker/pull/4078/files#diff-f7fc5bff7eaf66c1c00c00e72e6e16a2b93ec32f0cbd1f6e9da25866cf7f73b0.
So removing the invocation via `sh` and let the script decide which shell to use (most use `#!/usr/bin/env bash`)
Testrun in #1253
> Run e2e tests in bash

- control-plane/pkg/reconciler/consumergroup/consumergroup.go
- control-plane/pkg/reconciler/consumergroup/consumergroup_test.go
- control-plane/pkg/reconciler/testing/objects_broker.go
- control-plane/pkg/reconciler/testing/objects_channel.go
- control-plane/pkg/reconciler/testing/objects_common.go
- control-plane/pkg/reconciler/testing/objects_source.go
This ensures that our `consumergroup` controller as well as replication controller only match v2-specific pods and won't try to reconcile pods that belong to the previous deployment.
> [release-v1.15] Use v2 specific label to avoid matching previous deployment-based dispatchers

- control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_types.go
- control-plane/pkg/reconciler/channel/channel.go
- control-plane/pkg/reconciler/channel/channel_test.go
- control-plane/pkg/reconciler/consumer/consumer.go
- control-plane/pkg/reconciler/testing/objects_consumergroup.go
- control-plane/pkg/reconciler/trigger/v2/triggerv2.go
- control-plane/pkg/reconciler/trigger/v2/triggerv2_test.go
Previous to v2, we were setting `name` to the Broker or Channel name of the resource.
Cherry-pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/4120
> [release-v1.15] Set the `name` value for metrics tags to the correct top-level resource

- data-plane/contract/pom.xml
- data-plane/pom.xml
- openshift/ci-operator/static-images/dispatcher/Dockerfile
- openshift/ci-operator/static-images/dispatcher/hermetic/Dockerfile
- openshift/ci-operator/static-images/dispatcher/hermetic/Dockerfile.deps
- openshift/ci-operator/static-images/receiver/hermetic/Dockerfile
- openshift/ci-operator/static-images/receiver/hermetic/Dockerfile.deps
To support hermetic builds for Java, we will follow the POC here: https://github.com/openshift-knative/eventing-kafka-broker/pull/1273.
While this currently doesn't pass the enterprise contract, I've validated that it will in the future with Konflux team here: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1727247236771179 with the addition of `KONFLUX-298`.
This brings the dockerfiles and maven build changes from the POC https://github.com/openshift-knative/eventing-kafka-broker/pull/1273 and they will be used by pipelines introduced in https://github.com/openshift-knative/hack/pull/304
> [release-v1.15] Dockerfiles and build changes for hermetic Java builds

- control-plane/cmd/webhook-kafka/main.go
```
=== RUN   TestServerlessUpgradeContinual/Run/Steps/DowngradeWith/DowngradeServerless
triggerv2_downgrade.go:46: failed to downgrade from triggerv2 admission webhook "validation.webhook.kafka.eventing.knative.dev" denied the request: decoding request failed: cannot decode incoming old object: json: unknown field "topLevelResourceRef"
--- FAIL: TestServerlessUpgradeContinual/Run/Steps/DowngradeWith/DowngradeServerless (94.81s)
```
> SRVKE-1664: [release-v1.13] Disable disallow unknown fields

- control-plane/pkg/reconciler/consumergroup/auth.go
- control-plane/pkg/reconciler/consumergroup/consumergroup.go
The consumergroup reconciler was using the legacy secret format resolver to configure the Sarama client even in the Kafka Broker case.
We can't really add a E2E regression test as strimzi doesn't support `SASL/PLAIN`: see `strimzi/strimzi-kafka-operator/issues/2221`
> [release-v1.14] Fix EOF errors when using `SASL_SSL` `PLAIN`

- control-plane/pkg/reconciler/base/reconciler.go
- control-plane/pkg/reconciler/base/reconciler_test.go
- control-plane/pkg/reconciler/broker/broker.go
- control-plane/pkg/reconciler/broker/controller.go
- control-plane/pkg/reconciler/channel/channel.go
- control-plane/pkg/reconciler/channel/controller.go
- control-plane/pkg/reconciler/channel/v2/channelv2.go
- control-plane/pkg/reconciler/consumer/consumer.go
- control-plane/pkg/reconciler/sink/controller.go
- control-plane/pkg/reconciler/sink/kafka_sink.go
- control-plane/pkg/reconciler/trigger/trigger.go
- data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/file/FileWatcher.java
- data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/oidc/OIDCDiscoveryConfigListener.java
- data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
- data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/Main.java
- data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactory.java
- data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTest.java
- data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticleTracingTest.java
- data-plane/receiver/src/test/java/dev/knative/eventing/kafka/broker/receiver/main/ReceiverVerticleFactoryTest.java
- data-plane/tests/src/test/java/dev/knative/eventing/kafka/broker/tests/AbstractDataPlaneTest.java
Backports of the following:
* https://github.com/knative-extensions/eventing-kafka-broker/pull/4056
* https://github.com/openshift-knative/eventing-kafka-broker/pull/1355
> [release-1.14] fix: do not build OIDC config unless enabled 

- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/consumer/ConsumerVerticle.java
Completing the stop promise before the dependencies (dispatcher, client, etc) before will cause the WebClient to be closed.
> [release-v1.15] Complete Consumer verticle stop promise only after closing dependencies

- openshift/ci-operator/static-images/dispatcher/Dockerfile
- openshift/ci-operator/static-images/receiver/Dockerfile
Remove `.editorconfig` copy in Dockerfile as file was removed in https://github.com/knative-extensions/eventing-kafka-broker/pull/4096/files
Should help on https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-knative_eventing-kafka-broker/1489/pull-ci-openshift-knative-eventing-kafka-broker-release-next-417-images/1889113961492647936
> Remove .editorconfig copy in Dockerfile

- openshift/e2e-common.sh
- openshift/generate.sh
Fixing current issues with installing hack tools (e.g. [here](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-knative_eventing-kafka-broker/1535/pull-ci-openshift-knative-eventing-kafka-broker-release-v1.17-417-test-conformance/1891811011204222976))
```
Cloning into '/tmp/hack'...
+ cd /tmp/hack
+ go install github.com/openshift-knative/hack/cmd/generate
go: inconsistent vendoring in /tmp/hack:
...
```
> Run hack generate tool directly

- openshift/generate.sh
Fallback to default builder image based on golang & OCP image version (https://github.com/openshift-knative/hack/pull/601)
> Use default builder image in dockerfile generator

- data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/KReference.java
manual backport of 4330 from upstream
> [release-v1.16] In v1b3 the ET does have a Kreference.address

- data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/eventtype/KReference.java
manual backport of 4330 from upstream
> [release-v1.17] In v1b3 the ET does have a Kreference.address

- control-plane/pkg/reconciler/consumergroup/controller.go
- openshift/patches/sharedmain_MainNamed.patch
- openshift/release/generate-release.sh
- vendor/knative.dev/pkg/injection/sharedmain/main.go
SRVKE-1714
schedulers are created in the never disabled `consumergroup controller`, but when components on `KnativeKafka` are _not_ `enabled`, they report 404 from the API server.
This PR removes the undesired load from the API server as it does NOT create schedulers for _disabled_ components dispatchers (e.g. trigger, source or channel)
> [release-v1.16] Create schedulers on demand

- data-plane/receiver/src/main/java/dev/knative/eventing/kafka/broker/receiver/impl/ReceiverVerticle.java
Cherry-pick of https://github.com/knative-extensions/eventing-kafka-broker/pull/4360/files
Proposed fix for https://issues.redhat.com/browse/SRVKE-1720
> [release-v1.16] SRVKE-1720: Setup and initialize HTTPS server correctly when TLS config gets updated

- data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/main/ConsumerVerticleBuilder.java
Fix for https://issues.redhat.com/browse/SRVKE-1705 
```
Mar 03, 2025 7:20:11 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException: Cannot invoke "dev.knative.eventing.kafka.broker.core.ReactiveKafkaConsumer.exceptionHandler(io.vertx.core.Handler)" because "this.consumer" is null
at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.ConsumerVerticle.lambda$start$0(ConsumerVerticle.java:60)
at io.vertx.core.impl.future.FutureImpl$1.onSuccess(FutureImpl.java:91)
at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:66)
at io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:231)
at io.vertx.core.impl.future.FutureImpl.onSuccess(FutureImpl.java:87)
at dev.knative.eventing.kafka.broker.dispatcher.impl.consumer.ConsumerVe …
```
> [release-v1.16] SRVKE-1705 Fix initializer ocp

- control-plane/pkg/autoscaler/keda/keda.go
- control-plane/pkg/security/secrets_provider_legacy_channel_secret.go
- test/rekt/features/keda_scaling.go
* Fix KEDA scaling with SASL auth for brokers
TriggerAuthentication is misconfigured when Broker is configured to connect to Kafka with SASL since it was using only the legacy secret format.
* Adding nil check secret's data
https://issues.redhat.com/browse/SRVKE-1696
> [release-v1.16] Fix KEDA scaling with SASL auth for brokers (#4253)
